/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#if 0
// A non-working example of how to set up binding of a block
// Also used as a placeholder for CMakeLists.txt
#include <gnuradio/howto/example.h>

void bind_example(py::module& m)
{
    using example    = gr::howto::example;

    py::class_<example,gr::block, gr::basic_block,
        std::shared_ptr<example>>(m, "example")

        .def(py::init(&example::make),
            py::arg("arg1")
        )
        
        .def("fcn",&example::fcn)
        ;

} 
#endif
