/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <pmt/pmt_sugar.h>

void bind_pmt_sugar(py::module& m)
{


    m.def("mp",(pmt::pmt_t (*)(std::string const &))&pmt::mp,
        py::arg("s") 
    );
    m.def("mp",(pmt::pmt_t (*)(char const *))&pmt::mp,
        py::arg("s") 
    );
    m.def("mp",(pmt::pmt_t (*)(long int))&pmt::mp,
        py::arg("x") 
    );
    m.def("mp",(pmt::pmt_t (*)(long unsigned int))&pmt::mp,
        py::arg("x") 
    );
    m.def("mp",(pmt::pmt_t (*)(long long unsigned int))&pmt::mp,
        py::arg("x") 
    );
    m.def("mp",(pmt::pmt_t (*)(int))&pmt::mp,
        py::arg("x") 
    );
    m.def("mp",(pmt::pmt_t (*)(double))&pmt::mp,
        py::arg("x") 
    );
    m.def("mp",(pmt::pmt_t (*)(std::complex<double>))&pmt::mp,
        py::arg("z") 
    );
    m.def("mp",(pmt::pmt_t (*)(std::complex<float>))&pmt::mp,
        py::arg("z") 
    );
    // m.def("mp",(pmt::pmt_t (*)(std::shared_ptr<gr::messages::msg_accepter>))&pmt::mp,
    //     py::arg("ma") 
    // );
    m.def("mp",(pmt::pmt_t (*)(void const *, size_t))&pmt::mp,
        py::arg("data"), 
        py::arg("len_in_bytes") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &))&pmt::mp,
        py::arg("e0") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4"), 
        py::arg("e5") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4"), 
        py::arg("e5"), 
        py::arg("e6") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4"), 
        py::arg("e5"), 
        py::arg("e6"), 
        py::arg("e7") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4"), 
        py::arg("e5"), 
        py::arg("e6"), 
        py::arg("e7"), 
        py::arg("e8") 
    );
    m.def("mp",(pmt::pmt_t (*)(pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &, pmt::pmt_t const &))&pmt::mp,
        py::arg("e0"), 
        py::arg("e1"), 
        py::arg("e2"), 
        py::arg("e3"), 
        py::arg("e4"), 
        py::arg("e5"), 
        py::arg("e6"), 
        py::arg("e7"), 
        py::arg("e8"), 
        py::arg("e9") 
    );
} 
