/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/cpfsk_bc.h>

void bind_cpfsk_bc(py::module& m)
{
    using cpfsk_bc    = gr::analog::cpfsk_bc;


    py::class_<cpfsk_bc,gr::sync_interpolator, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cpfsk_bc>>(m, "cpfsk_bc")

        .def(py::init(&cpfsk_bc::make),
           py::arg("k"), 
           py::arg("ampl"), 
           py::arg("samples_per_sym") 
        )
        

        .def("set_amplitude",&cpfsk_bc::set_amplitude,
            py::arg("amplitude") 
        )
        .def("amplitude",&cpfsk_bc::amplitude)
        .def("freq",&cpfsk_bc::freq)
        .def("phase",&cpfsk_bc::phase)
        ;


} 
