/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/cpm.h>
// pydoc.h is automatically generated in the build directory
#include <cpm_pydoc.h>

void bind_cpm(py::module& m)
{

    using cpm    = ::gr::analog::cpm;


    py::class_<cpm,
        std::shared_ptr<cpm>>(m, "cpm", D(cpm))

        .def(py::init<>(),D(cpm,cpm,0))
        .def(py::init<gr::analog::cpm const &>(),           py::arg("arg0"),
           D(cpm,cpm,1)
        )


        .def_static("phase_response",&cpm::phase_response,
            py::arg("type"),
            py::arg("samples_per_sym"),
            py::arg("L"),
            py::arg("beta") = 0.29999999999999999,
            D(cpm,phase_response)
        )

        ;




}







