/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/fmdet_cf.h>

void bind_fmdet_cf(py::module& m)
{
    using fmdet_cf    = gr::analog::fmdet_cf;


    py::class_<fmdet_cf,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fmdet_cf>>(m, "fmdet_cf")

        .def(py::init(&fmdet_cf::make),
           py::arg("samplerate"), 
           py::arg("freq_low"), 
           py::arg("freq_high"), 
           py::arg("scl") 
        )
        

        .def("set_scale",&fmdet_cf::set_scale,
            py::arg("scl") 
        )
        .def("set_freq_range",&fmdet_cf::set_freq_range,
            py::arg("freq_low"), 
            py::arg("freq_high") 
        )
        .def("freq",&fmdet_cf::freq)
        .def("freq_high",&fmdet_cf::freq_high)
        .def("freq_low",&fmdet_cf::freq_low)
        .def("scale",&fmdet_cf::scale)
        .def("bias",&fmdet_cf::bias)
        ;


} 
