/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/probe_avg_mag_sqrd_cf.h>

void bind_probe_avg_mag_sqrd_cf(py::module& m)
{
    using probe_avg_mag_sqrd_cf    = gr::analog::probe_avg_mag_sqrd_cf;


    py::class_<probe_avg_mag_sqrd_cf,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<probe_avg_mag_sqrd_cf>>(m, "probe_avg_mag_sqrd_cf")

        .def(py::init(&probe_avg_mag_sqrd_cf::make),
           py::arg("threshold_db"), 
           py::arg("alpha") = 1.0E-4 
        )
        

        .def("unmuted",&probe_avg_mag_sqrd_cf::unmuted)
        .def("level",&probe_avg_mag_sqrd_cf::level)
        .def("threshold",&probe_avg_mag_sqrd_cf::threshold)
        .def("set_alpha",&probe_avg_mag_sqrd_cf::set_alpha,
            py::arg("alpha") 
        )
        .def("set_threshold",&probe_avg_mag_sqrd_cf::set_threshold,
            py::arg("decibels") 
        )
        .def("reset",&probe_avg_mag_sqrd_cf::reset)
        ;


} 
