/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/probe_avg_mag_sqrd_c.h>

void bind_probe_avg_mag_sqrd_c(py::module& m)
{
    using probe_avg_mag_sqrd_c    = gr::analog::probe_avg_mag_sqrd_c;


    py::class_<probe_avg_mag_sqrd_c,gr::sync_block,
        std::shared_ptr<probe_avg_mag_sqrd_c>>(m, "probe_avg_mag_sqrd_c")

        .def(py::init(&probe_avg_mag_sqrd_c::make),
           py::arg("threshold_db"), 
           py::arg("alpha") = 1.0E-4 
        )
        

        .def("unmuted",&probe_avg_mag_sqrd_c::unmuted)
        .def("level",&probe_avg_mag_sqrd_c::level)
        .def("threshold",&probe_avg_mag_sqrd_c::threshold)
        .def("set_alpha",&probe_avg_mag_sqrd_c::set_alpha,
            py::arg("alpha") 
        )
        .def("set_threshold",&probe_avg_mag_sqrd_c::set_threshold,
            py::arg("decibels") 
        )
        .def("reset",&probe_avg_mag_sqrd_c::reset)
        .def("to_basic_block",[](std::shared_ptr<probe_avg_mag_sqrd_c> p){
            return p->to_basic_block();
        })
        ;


} 
