/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/probe_avg_mag_sqrd_f.h>

void bind_probe_avg_mag_sqrd_f(py::module& m)
{
    using probe_avg_mag_sqrd_f    = gr::analog::probe_avg_mag_sqrd_f;


    py::class_<probe_avg_mag_sqrd_f,gr::sync_block,
        std::shared_ptr<probe_avg_mag_sqrd_f>>(m, "probe_avg_mag_sqrd_f")

        .def(py::init(&probe_avg_mag_sqrd_f::make),
           py::arg("threshold_db"), 
           py::arg("alpha") = 1.0E-4 
        )
        

        .def("unmuted",&probe_avg_mag_sqrd_f::unmuted)
        .def("level",&probe_avg_mag_sqrd_f::level)
        .def("threshold",&probe_avg_mag_sqrd_f::threshold)
        .def("set_alpha",&probe_avg_mag_sqrd_f::set_alpha,
            py::arg("alpha") 
        )
        .def("set_threshold",&probe_avg_mag_sqrd_f::set_threshold,
            py::arg("decibels") 
        )
        .def("reset",&probe_avg_mag_sqrd_f::reset)
        .def("to_basic_block",[](std::shared_ptr<probe_avg_mag_sqrd_f> p){
            return p->to_basic_block();
        })
        ;


} 
