/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/pwr_squelch_cc.h>

void bind_pwr_squelch_cc(py::module& m)
{
    using pwr_squelch_cc    = gr::analog::pwr_squelch_cc;


    py::class_<pwr_squelch_cc,gr::analog::squelch_base_cc,
        std::shared_ptr<pwr_squelch_cc>>(m, "pwr_squelch_cc")

        .def(py::init(&pwr_squelch_cc::make),
           py::arg("db"), 
           py::arg("alpha") = 1.0E-4, 
           py::arg("ramp") = 0, 
           py::arg("gate") = false 
        )
        

        .def("squelch_range",&pwr_squelch_cc::squelch_range)
        .def("threshold",&pwr_squelch_cc::threshold)
        .def("set_threshold",&pwr_squelch_cc::set_threshold,
            py::arg("db") 
        )
        .def("set_alpha",&pwr_squelch_cc::set_alpha,
            py::arg("alpha") 
        )
        .def("ramp",&pwr_squelch_cc::ramp)
        .def("set_ramp",&pwr_squelch_cc::set_ramp,
            py::arg("ramp") 
        )
        .def("gate",&pwr_squelch_cc::gate)
        .def("set_gate",&pwr_squelch_cc::set_gate,
            py::arg("gate") 
        )
        .def("unmuted",&pwr_squelch_cc::unmuted)
        .def("to_basic_block",[](std::shared_ptr<pwr_squelch_cc> p){
            return p->to_basic_block();
        })
        ;


} 
