/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/analog/simple_squelch_cc.h>

void bind_simple_squelch_cc(py::module& m)
{
    using simple_squelch_cc    = gr::analog::simple_squelch_cc;


    py::class_<simple_squelch_cc,gr::sync_block,
        std::shared_ptr<simple_squelch_cc>>(m, "simple_squelch_cc")

        .def(py::init(&simple_squelch_cc::make),
           py::arg("threshold_db"), 
           py::arg("alpha") 
        )
        

        .def("unmuted",&simple_squelch_cc::unmuted)
        .def("set_alpha",&simple_squelch_cc::set_alpha,
            py::arg("alpha") 
        )
        .def("set_threshold",&simple_squelch_cc::set_threshold,
            py::arg("decibels") 
        )
        .def("threshold",&simple_squelch_cc::threshold)
        .def("squelch_range",&simple_squelch_cc::squelch_range)
        .def("to_basic_block",[](std::shared_ptr<simple_squelch_cc> p){
            return p->to_basic_block();
        })
        ;


} 
