/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zeromq/rep_msg_sink.h>

void bind_rep_msg_sink(py::module& m)
{
    using rep_msg_sink    = gr::zeromq::rep_msg_sink;


    py::class_<rep_msg_sink,gr::block,
        std::shared_ptr<rep_msg_sink>>(m, "rep_msg_sink")

        .def(py::init(&rep_msg_sink::make),
           py::arg("address"), 
           py::arg("timeout") = 100 
        )
        

        .def("last_endpoint",&rep_msg_sink::last_endpoint)
        .def("to_basic_block",[](std::shared_ptr<rep_msg_sink> p){
            return p->to_basic_block();
        })
        ;


} 
