/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zeromq/req_msg_source.h>

void bind_req_msg_source(py::module& m)
{
    using req_msg_source    = gr::zeromq::req_msg_source;


    py::class_<req_msg_source,gr::block,
        std::shared_ptr<req_msg_source>>(m, "req_msg_source")

        .def(py::init(&req_msg_source::make),
           py::arg("address"), 
           py::arg("timeout") = 100 
        )
        

        .def("last_endpoint",&req_msg_source::last_endpoint)
        .def("to_basic_block",[](std::shared_ptr<req_msg_source> p){
            return p->to_basic_block();
        })
        ;


} 
