/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zeromq/sub_source.h>

void bind_sub_source(py::module& m)
{
    using sub_source    = gr::zeromq::sub_source;


    py::class_<sub_source,gr::sync_block,
        std::shared_ptr<sub_source>>(m, "sub_source")

        .def(py::init(&sub_source::make),
           py::arg("itemsize"), 
           py::arg("vlen"), 
           py::arg("address"), 
           py::arg("timeout") = 100, 
           py::arg("pass_tags") = false, 
           py::arg("hwm") = -1 
        )
        

        .def("last_endpoint",&sub_source::last_endpoint)
        .def("to_basic_block",[](std::shared_ptr<sub_source> p){
            return p->to_basic_block();
        })
        ;


} 
