//
// Copyright 2017-2018 Ettus Research, a National Instruments Company
// Copyright 2019 Ettus Research, a National Instruments Brand
//
// SPDX-License-Identifier: GPL-3.0-or-later
//

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
#include <numpy/arrayobject.h>

namespace py = pybind11;

// Bindings listed in this block will be changed by modtool
// <auto-generated-python-bindings>
#include "bindings/file_source_python.hpp"
#include "bindings/head_python.hpp"
// </auto-generated-python-bindings>
// Bindings listing in this block will be left alone
// <manually-generated-python-bindings>
#include "bindings/vector_source_python.hpp"
#include "bindings/vector_sink_python.hpp"
#include "bindings/null_sink_python.hpp"
#include "bindings/multiply_const_python.hpp"
#include "bindings/stream_to_vector_python.hpp"
// </manually-generated-python-bindings>


// We need this hack because import_array() returns NULL
// for newer Python versions.
// This function is also necessary because it ensures access to the C API
// and removes a warning.
// #if PY_MAJOR_VERSION >= 3
void* init_numpy()
{
    import_array();
    return NULL;
}
// #else
// void init_numpy()
// {
    // import_array();
// }
// #endif




PYBIND11_MODULE(blocks_python, m)
{
    // Initialize the numpy C API
    // (otherwise we will see segmentation faults)
    init_numpy();
    
    py::module::import("gnuradio.gr");

    // Register types submodule
    // bind_pmt(m);
    // bind_basic_block(m);

// <auto-generated-python-bindings>
    bind_file_source(m);
    bind_head(m);
// </auto-generated-python-bindings>
// <manually-generated-python-bindings>
    bind_vector_source(m);
    bind_vector_sink(m);
    bind_null_sink(m);
    bind_multiply_const(m);
    bind_stream_to_vector(m);
// </manually-generated-python-bindings>


}

