/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/channels/selective_fading_model.h>

void bind_selective_fading_model(py::module& m)
{
    using selective_fading_model    = gr::channels::selective_fading_model;


    py::class_<selective_fading_model,gr::sync_block,
        std::shared_ptr<selective_fading_model>>(m, "selective_fading_model")

        .def(py::init(&selective_fading_model::make),
           py::arg("N"), 
           py::arg("fDTs"), 
           py::arg("LOS"), 
           py::arg("K"), 
           py::arg("seed"), 
           py::arg("delays"), 
           py::arg("mags"), 
           py::arg("ntaps") 
        )
        

        .def("fDTs",&selective_fading_model::fDTs)
        .def("K",&selective_fading_model::K)
        .def("step",&selective_fading_model::step)
        .def("set_fDTs",&selective_fading_model::set_fDTs,
            py::arg("fDTs") 
        )
        .def("set_K",&selective_fading_model::set_K,
            py::arg("K") 
        )
        .def("set_step",&selective_fading_model::set_step,
            py::arg("step") 
        )
        .def("to_basic_block",[](std::shared_ptr<selective_fading_model> p){
            return p->to_basic_block();
        })
        ;


} 
