/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/crc32.h>

void bind_crc32(py::module& m)
{


    m.def("update_crc32",(unsigned int (*)(unsigned int, const unsigned char*, size_t))&gr::digital::update_crc32,
        py::arg("crc"), 
        py::arg("buf"), 
        py::arg("len") 
    );
    m.def("update_crc32",(unsigned int (*)(unsigned int, const std::string))&gr::digital::update_crc32,
        py::arg("crc"), 
        py::arg("buf") 
    );
    m.def("crc32",(unsigned int (*)(const unsigned char*, size_t))&gr::digital::crc32,
        py::arg("buf"), 
        py::arg("len") 
    );
    m.def("crc32",(unsigned int (*)(const std::string))&gr::digital::crc32,
        py::arg("buf") 
    );
} 
