/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/glfsr_source_b.h>

void bind_glfsr_source_b(py::module& m)
{
    using glfsr_source_b    = gr::digital::glfsr_source_b;


    py::class_<glfsr_source_b,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<glfsr_source_b>>(m, "glfsr_source_b")

        .def(py::init(&glfsr_source_b::make),
           py::arg("degree"), 
           py::arg("repeat") = true, 
           py::arg("mask") = 0, 
           py::arg("seed") = 1 
        )
        

        .def("period",&glfsr_source_b::period)
        .def("mask",&glfsr_source_b::mask)
        ;


} 
