/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/lfsr.h>

void bind_lfsr(py::module& m)
{
    using lfsr    = gr::digital::lfsr;


    py::class_<lfsr,
        std::shared_ptr<lfsr>>(m, "lfsr")

        .def(py::init<uint32_t,uint32_t,uint32_t>(),           py::arg("mask"), 
           py::arg("seed"), 
           py::arg("reg_len") 
        )
        .def(py::init<gr::digital::lfsr const &>(),           py::arg("arg0") 
        )

        .def("next_bit",&lfsr::next_bit)
        .def("next_bit_scramble",&lfsr::next_bit_scramble,
            py::arg("input") 
        )
        .def("next_bit_descramble",&lfsr::next_bit_descramble,
            py::arg("input") 
        )
        .def("reset",&lfsr::reset)
        .def("pre_shift",&lfsr::pre_shift,
            py::arg("num") 
        )
        .def("mask",&lfsr::mask)
        ;


} 
