/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/lms_dd_equalizer_cc.h>

void bind_lms_dd_equalizer_cc(py::module& m)
{
    using lms_dd_equalizer_cc    = gr::digital::lms_dd_equalizer_cc;


    py::class_<lms_dd_equalizer_cc,gr::sync_decimator,
        std::shared_ptr<lms_dd_equalizer_cc>>(m, "lms_dd_equalizer_cc")

        .def(py::init(&lms_dd_equalizer_cc::make),
           py::arg("num_taps"), 
           py::arg("mu"), 
           py::arg("sps"), 
           py::arg("cnst") 
        )
        

        .def("set_taps",&lms_dd_equalizer_cc::set_taps,
            py::arg("taps") 
        )
        .def("taps",&lms_dd_equalizer_cc::taps)
        .def("gain",&lms_dd_equalizer_cc::gain)
        .def("set_gain",&lms_dd_equalizer_cc::set_gain,
            py::arg("mu") 
        )
        .def("to_basic_block",[](std::shared_ptr<lms_dd_equalizer_cc> p){
            return p->to_basic_block();
        })
        ;


} 
