/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/msk_timing_recovery_cc.h>

void bind_msk_timing_recovery_cc(py::module& m)
{
    using msk_timing_recovery_cc    = gr::digital::msk_timing_recovery_cc;


    py::class_<msk_timing_recovery_cc,gr::block, gr::basic_block,
        std::shared_ptr<msk_timing_recovery_cc>>(m, "msk_timing_recovery_cc")

        .def(py::init(&msk_timing_recovery_cc::make),
           py::arg("sps"), 
           py::arg("gain"), 
           py::arg("limit"), 
           py::arg("osps") 
        )
        

        .def("set_gain",&msk_timing_recovery_cc::set_gain,
            py::arg("gain") 
        )
        .def("get_gain",&msk_timing_recovery_cc::get_gain)
        .def("set_limit",&msk_timing_recovery_cc::set_limit,
            py::arg("limit") 
        )
        .def("get_limit",&msk_timing_recovery_cc::get_limit)
        .def("set_sps",&msk_timing_recovery_cc::set_sps,
            py::arg("sps") 
        )
        .def("get_sps",&msk_timing_recovery_cc::get_sps)
        ;


} 
