/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/ofdm_frame_equalizer_vcvc.h>

void bind_ofdm_frame_equalizer_vcvc(py::module& m)
{
    using ofdm_frame_equalizer_vcvc    = gr::digital::ofdm_frame_equalizer_vcvc;


    py::class_<ofdm_frame_equalizer_vcvc,gr::tagged_stream_block,
        std::shared_ptr<ofdm_frame_equalizer_vcvc>>(m, "ofdm_frame_equalizer_vcvc")

        .def(py::init(&ofdm_frame_equalizer_vcvc::make),
           py::arg("equalizer"), 
           py::arg("cp_len"), 
           py::arg("tsb_key") = "frame_len", 
           py::arg("propagate_channel_state") = false, 
           py::arg("fixed_frame_len") = 0 
        )
        

        .def("to_basic_block",[](std::shared_ptr<ofdm_frame_equalizer_vcvc> p){
            return p->to_basic_block();
        })
        ;


} 
