/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/ofdm_equalizer_simpledfe.h>

void bind_ofdm_equalizer_simpledfe(py::module& m)
{
    using ofdm_equalizer_simpledfe    = gr::digital::ofdm_equalizer_simpledfe;


    py::class_<ofdm_equalizer_simpledfe,gr::digital::ofdm_equalizer_1d_pilots,
        std::shared_ptr<ofdm_equalizer_simpledfe>>(m, "ofdm_equalizer_simpledfe")

        .def(py::init(&ofdm_equalizer_simpledfe::make),
           py::arg("fft_len"), 
           py::arg("constellation"), 
           py::arg("occupied_carriers") = std::vector<std::vector<int> >(), 
           py::arg("pilot_carriers") = std::vector<std::vector<int> >(), 
           py::arg("pilot_symbols") = std::vector<std::vector<gr_complex> >(), 
           py::arg("symbols_skipped") = 0, 
           py::arg("alpha") = 0.1, 
           py::arg("input_is_shifted") = true 
        )
        

        .def("equalize",&ofdm_equalizer_simpledfe::equalize,
            py::arg("frame"), 
            py::arg("n_sym"), 
            py::arg("initial_taps") = std::vector<gr_complex>(), 
            py::arg("tags") = std::vector<gr::tag_t>() 
        )
        ;


} 
