/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/probe_density_b.h>

void bind_probe_density_b(py::module& m)
{
    using probe_density_b    = gr::digital::probe_density_b;


    py::class_<probe_density_b,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<probe_density_b>>(m, "probe_density_b")

        .def(py::init(&probe_density_b::make),
           py::arg("alpha") 
        )
        

        .def("density",&probe_density_b::density)
        .def("set_alpha",&probe_density_b::set_alpha,
            py::arg("alpha") 
        )
        ;


} 
