/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/probe_mpsk_snr_est_c.h>

void bind_probe_mpsk_snr_est_c(py::module& m)
{
    using probe_mpsk_snr_est_c    = gr::digital::probe_mpsk_snr_est_c;


    py::class_<probe_mpsk_snr_est_c,gr::sync_block,
        std::shared_ptr<probe_mpsk_snr_est_c>>(m, "probe_mpsk_snr_est_c")

        .def(py::init(&probe_mpsk_snr_est_c::make),
           py::arg("type"), 
           py::arg("msg_nsamples") = 10000, 
           py::arg("alpha") = 0.001 
        )
        

        .def("snr",&probe_mpsk_snr_est_c::snr)
        .def("signal",&probe_mpsk_snr_est_c::signal)
        .def("noise",&probe_mpsk_snr_est_c::noise)
        .def("type",&probe_mpsk_snr_est_c::type)
        .def("msg_nsample",&probe_mpsk_snr_est_c::msg_nsample)
        .def("alpha",&probe_mpsk_snr_est_c::alpha)
        .def("set_type",&probe_mpsk_snr_est_c::set_type,
            py::arg("t") 
        )
        .def("set_msg_nsample",&probe_mpsk_snr_est_c::set_msg_nsample,
            py::arg("n") 
        )
        .def("set_alpha",&probe_mpsk_snr_est_c::set_alpha,
            py::arg("alpha") 
        )
        .def("to_basic_block",[](std::shared_ptr<probe_mpsk_snr_est_c> p){
            return p->to_basic_block();
        })
        ;


} 
