/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/protocol_formatter_bb.h>

void bind_protocol_formatter_bb(py::module& m)
{
    using protocol_formatter_bb    = gr::digital::protocol_formatter_bb;


    py::class_<protocol_formatter_bb, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<protocol_formatter_bb>>(m, "protocol_formatter_bb")

        .def(py::init(&protocol_formatter_bb::make),
           py::arg("format"), 
           py::arg("len_tag_key") = "packet_len" 
        )
        

        .def("set_header_format",&protocol_formatter_bb::set_header_format,
            py::arg("format") 
        )
        ;


} 
