/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/protocol_parser_b.h>

void bind_protocol_parser_b(py::module& m)
{
    using protocol_parser_b    = gr::digital::protocol_parser_b;


    py::class_<protocol_parser_b,gr::sync_block,
        std::shared_ptr<protocol_parser_b>>(m, "protocol_parser_b")

        .def(py::init(&protocol_parser_b::make),
           py::arg("format") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<protocol_parser_b> p){
            return p->to_basic_block();
        })
        ;


} 
