/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/vocoder/alaw_decode_bs.h>

void bind_alaw_decode_bs(py::module& m)
{
    using alaw_decode_bs    = gr::vocoder::alaw_decode_bs;


    py::class_<alaw_decode_bs,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<alaw_decode_bs>>(m, "alaw_decode_bs")

        .def(py::init(&alaw_decode_bs::make)
        )
        ;


} 
