/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/vocoder/gsm_fr_decode_ps.h>

void bind_gsm_fr_decode_ps(py::module& m)
{
    using gsm_fr_decode_ps    = gr::vocoder::gsm_fr_decode_ps;


    py::class_<gsm_fr_decode_ps,gr::sync_interpolator,
        std::shared_ptr<gsm_fr_decode_ps>>(m, "gsm_fr_decode_ps")

        .def(py::init(&gsm_fr_decode_ps::make)
        )
        

        .def("to_basic_block",[](std::shared_ptr<gsm_fr_decode_ps> p){
            return p->to_basic_block();
        })
        ;


} 
