/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/dc_blocker_cc.h>

void bind_dc_blocker_cc(py::module& m)
{
    using dc_blocker_cc    = gr::filter::dc_blocker_cc;


    py::class_<dc_blocker_cc,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dc_blocker_cc>>(m, "dc_blocker_cc")

        .def(py::init(&dc_blocker_cc::make),
           py::arg("D"), 
           py::arg("long_form") 
        )
        

        .def("group_delay",&dc_blocker_cc::group_delay)
        ;


} 
