/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/fft_filter_ccf.h>

void bind_fft_filter_ccf(py::module& m)
{
    using fft_filter_ccf    = gr::filter::fft_filter_ccf;


    py::class_<fft_filter_ccf,gr::sync_decimator,
        std::shared_ptr<fft_filter_ccf>>(m, "fft_filter_ccf")

        .def(py::init(&fft_filter_ccf::make),
           py::arg("decimation"), 
           py::arg("taps"), 
           py::arg("nthreads") = 1 
        )
        

        .def("set_taps",&fft_filter_ccf::set_taps,
            py::arg("taps") 
        )
        .def("taps",&fft_filter_ccf::taps)
        .def("set_nthreads",&fft_filter_ccf::set_nthreads,
            py::arg("n") 
        )
        .def("nthreads",&fft_filter_ccf::nthreads)
        .def("to_basic_block",[](std::shared_ptr<fft_filter_ccf> p){
            return p->to_basic_block();
        })
        ;


} 
