/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/filterbank.h>

void bind_filterbank(py::module& m)
{
    using filterbank    = gr::filter::kernel::filterbank;


    py::class_<filterbank,
        std::shared_ptr<filterbank>>(m, "filterbank")

        .def(py::init<std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const &>(),           py::arg("taps") 
        )
        .def(py::init<gr::filter::kernel::filterbank const &>(),           py::arg("arg0") 
        )

        .def("set_taps",&filterbank::set_taps,
            py::arg("taps") 
        )
        .def("print_taps",&filterbank::print_taps)
        .def("taps",&filterbank::taps)
        ;


} 
