/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/filterbank_vcvcf.h>

void bind_filterbank_vcvcf(py::module& m)
{
    using filterbank_vcvcf    = gr::filter::filterbank_vcvcf;


    py::class_<filterbank_vcvcf,gr::block,
        std::shared_ptr<filterbank_vcvcf>>(m, "filterbank_vcvcf")

        .def(py::init(&filterbank_vcvcf::make),
           py::arg("taps") 
        )
        

        .def("set_taps",&filterbank_vcvcf::set_taps,
            py::arg("taps") 
        )
        .def("print_taps",&filterbank_vcvcf::print_taps)
        .def("taps",&filterbank_vcvcf::taps)
        .def("to_basic_block",[](std::shared_ptr<filterbank_vcvcf> p){
            return p->to_basic_block();
        })
        ;


} 
