/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/mmse_resampler_cc.h>

void bind_mmse_resampler_cc(py::module& m)
{
    using mmse_resampler_cc    = gr::filter::mmse_resampler_cc;


    py::class_<mmse_resampler_cc,gr::block,
        std::shared_ptr<mmse_resampler_cc>>(m, "mmse_resampler_cc")

        .def(py::init(&mmse_resampler_cc::make),
           py::arg("phase_shift"), 
           py::arg("resamp_ratio") 
        )
        

        .def("mu",&mmse_resampler_cc::mu)
        .def("resamp_ratio",&mmse_resampler_cc::resamp_ratio)
        .def("set_mu",&mmse_resampler_cc::set_mu,
            py::arg("mu") 
        )
        .def("set_resamp_ratio",&mmse_resampler_cc::set_resamp_ratio,
            py::arg("resamp_ratio") 
        )
        .def("to_basic_block",[](std::shared_ptr<mmse_resampler_cc> p){
            return p->to_basic_block();
        })
        ;


} 
