/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/mmse_fir_interpolator_cc.h>

void bind_mmse_fir_interpolator_cc(py::module& m)
{
    using mmse_fir_interpolator_cc    = gr::filter::mmse_fir_interpolator_cc;


    py::class_<mmse_fir_interpolator_cc,
        std::shared_ptr<mmse_fir_interpolator_cc>>(m, "mmse_fir_interpolator_cc")

        .def(py::init<>())
        .def(py::init<gr::filter::mmse_fir_interpolator_cc const &>(),           py::arg("arg0") 
        )

        .def("ntaps",&mmse_fir_interpolator_cc::ntaps)
        .def("nsteps",&mmse_fir_interpolator_cc::nsteps)
        .def("interpolate",&mmse_fir_interpolator_cc::interpolate,
            py::arg("input"), 
            py::arg("mu") 
        )
        ;


} 
