/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/pfb_arb_resampler_fff.h>

void bind_pfb_arb_resampler_fff(py::module& m)
{
    using pfb_arb_resampler_fff    = gr::filter::pfb_arb_resampler_fff;


    py::class_<pfb_arb_resampler_fff,gr::block,
        std::shared_ptr<pfb_arb_resampler_fff>>(m, "pfb_arb_resampler_fff")

        .def(py::init(&pfb_arb_resampler_fff::make),
           py::arg("rate"), 
           py::arg("taps"), 
           py::arg("filter_size") = 32 
        )
        

        .def("set_taps",&pfb_arb_resampler_fff::set_taps,
            py::arg("taps") 
        )
        .def("taps",&pfb_arb_resampler_fff::taps)
        .def("print_taps",&pfb_arb_resampler_fff::print_taps)
        .def("set_rate",&pfb_arb_resampler_fff::set_rate,
            py::arg("rate") 
        )
        .def("set_phase",&pfb_arb_resampler_fff::set_phase,
            py::arg("ph") 
        )
        .def("phase",&pfb_arb_resampler_fff::phase)
        .def("taps_per_filter",&pfb_arb_resampler_fff::taps_per_filter)
        .def("interpolation_rate",&pfb_arb_resampler_fff::interpolation_rate)
        .def("decimation_rate",&pfb_arb_resampler_fff::decimation_rate)
        .def("fractional_rate",&pfb_arb_resampler_fff::fractional_rate)
        .def("group_delay",&pfb_arb_resampler_fff::group_delay)
        .def("phase_offset",&pfb_arb_resampler_fff::phase_offset,
            py::arg("freq"), 
            py::arg("fs") 
        )
        .def("to_basic_block",[](std::shared_ptr<pfb_arb_resampler_fff> p){
            return p->to_basic_block();
        })
        ;


} 
