/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/filter/polyphase_filterbank.h>

void bind_polyphase_filterbank(py::module& m)
{
    using polyphase_filterbank    = gr::filter::kernel::polyphase_filterbank;


    py::class_<polyphase_filterbank,
        std::shared_ptr<polyphase_filterbank>>(m, "polyphase_filterbank")

        .def(py::init<unsigned int,std::vector<float, std::allocator<float> > const &,bool>(),           py::arg("nfilts"), 
           py::arg("taps"), 
           py::arg("fft_forward") = false 
        )
        .def(py::init<gr::filter::kernel::polyphase_filterbank const &>(),           py::arg("arg0") 
        )

        .def("set_taps",&polyphase_filterbank::set_taps,
            py::arg("taps") 
        )
        .def("print_taps",&polyphase_filterbank::print_taps)
        .def("taps",&polyphase_filterbank::taps)
        ;


} 
