/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_rs_encoder.h>

void bind_atsc_rs_encoder(py::module& m)
{
    using atsc_rs_encoder    = gr::dtv::atsc_rs_encoder;


    py::class_<atsc_rs_encoder,gr::sync_block,
        std::shared_ptr<atsc_rs_encoder>>(m, "atsc_rs_encoder")

        .def(py::init(&atsc_rs_encoder::make)
        )
        

        .def("to_basic_block",[](std::shared_ptr<atsc_rs_encoder> p){
            return p->to_basic_block();
        })
        ;


} 
