/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_derandomizer.h>

void bind_atsc_derandomizer(py::module& m)
{
    using atsc_derandomizer    = gr::dtv::atsc_derandomizer;


    py::class_<atsc_derandomizer,gr::sync_block,
        std::shared_ptr<atsc_derandomizer>>(m, "atsc_derandomizer")

        .def(py::init(&atsc_derandomizer::make)
        )
        

        .def("to_basic_block",[](std::shared_ptr<atsc_derandomizer> p){
            return p->to_basic_block();
        })
        ;


} 
