/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_pad.h>

void bind_atsc_pad(py::module& m)
{
    using atsc_pad    = gr::dtv::atsc_pad;


    py::class_<atsc_pad,gr::sync_decimator,
        std::shared_ptr<atsc_pad>>(m, "atsc_pad")

        .def(py::init(&atsc_pad::make)
        )
        

        .def("to_basic_block",[](std::shared_ptr<atsc_pad> p){
            return p->to_basic_block();
        })
        ;


} 
