/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_equalizer.h>

void bind_atsc_equalizer(py::module& m)
{
    using atsc_equalizer    = gr::dtv::atsc_equalizer;


    py::class_<atsc_equalizer,gr::block,
        std::shared_ptr<atsc_equalizer>>(m, "atsc_equalizer")

        .def(py::init(&atsc_equalizer::make)
        )
        

        .def("taps",&atsc_equalizer::taps)
        .def("data",&atsc_equalizer::data)
        .def("to_basic_block",[](std::shared_ptr<atsc_equalizer> p){
            return p->to_basic_block();
        })
        ;


} 
