/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_viterbi_decoder.h>

void bind_atsc_viterbi_decoder(py::module& m)
{
    using atsc_viterbi_decoder    = gr::dtv::atsc_viterbi_decoder;


    py::class_<atsc_viterbi_decoder,gr::sync_block,
        std::shared_ptr<atsc_viterbi_decoder>>(m, "atsc_viterbi_decoder")

        .def(py::init(&atsc_viterbi_decoder::make)
        )
        

        .def("decoder_metrics",&atsc_viterbi_decoder::decoder_metrics)
        .def("to_basic_block",[](std::shared_ptr<atsc_viterbi_decoder> p){
            return p->to_basic_block();
        })
        ;


} 
