/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_sync.h>

void bind_atsc_sync(py::module& m)
{
    using atsc_sync    = gr::dtv::atsc_sync;


    py::class_<atsc_sync,gr::block,
        std::shared_ptr<atsc_sync>>(m, "atsc_sync")

        .def(py::init(&atsc_sync::make),
           py::arg("rate") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<atsc_sync> p){
            return p->to_basic_block();
        })
        ;


} 
