/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/catv_randomizer_bb.h>

void bind_catv_randomizer_bb(py::module& m)
{
    using catv_randomizer_bb    = gr::dtv::catv_randomizer_bb;


    py::class_<catv_randomizer_bb,gr::sync_block,
        std::shared_ptr<catv_randomizer_bb>>(m, "catv_randomizer_bb")

        .def(py::init(&catv_randomizer_bb::make),
           py::arg("constellation") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<catv_randomizer_bb> p){
            return p->to_basic_block();
        })
        ;


} 
