/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/dvb_ldpc_bb.h>

void bind_dvb_ldpc_bb(py::module& m)
{
    using dvb_ldpc_bb    = gr::dtv::dvb_ldpc_bb;


    py::class_<dvb_ldpc_bb,gr::block,
        std::shared_ptr<dvb_ldpc_bb>>(m, "dvb_ldpc_bb")

        .def(py::init(&dvb_ldpc_bb::make),
           py::arg("standard"), 
           py::arg("framesize"), 
           py::arg("rate"), 
           py::arg("constellation") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<dvb_ldpc_bb> p){
            return p->to_basic_block();
        })
        ;


} 
