/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/dvbt_bit_inner_deinterleaver.h>

void bind_dvbt_bit_inner_deinterleaver(py::module& m)
{
    using dvbt_bit_inner_deinterleaver    = gr::dtv::dvbt_bit_inner_deinterleaver;


    py::class_<dvbt_bit_inner_deinterleaver,gr::block,
        std::shared_ptr<dvbt_bit_inner_deinterleaver>>(m, "dvbt_bit_inner_deinterleaver")

        .def(py::init(&dvbt_bit_inner_deinterleaver::make),
           py::arg("nsize"), 
           py::arg("constellation"), 
           py::arg("hierarchy"), 
           py::arg("transmission") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<dvbt_bit_inner_deinterleaver> p){
            return p->to_basic_block();
        })
        ;


} 
