/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/dvbt_convolutional_deinterleaver.h>

void bind_dvbt_convolutional_deinterleaver(py::module& m)
{
    using dvbt_convolutional_deinterleaver    = gr::dtv::dvbt_convolutional_deinterleaver;


    py::class_<dvbt_convolutional_deinterleaver,gr::block, gr::basic_block,
        std::shared_ptr<dvbt_convolutional_deinterleaver>>(m, "dvbt_convolutional_deinterleaver")

        .def(py::init(&dvbt_convolutional_deinterleaver::make),
           py::arg("nsize"), 
           py::arg("I"), 
           py::arg("M") 
        )
        ;


} 
