/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/add_const_bb.h>

void bind_add_const_bb(py::module& m)
{
    using add_const_bb    = gr::blocks::add_const_bb;


    py::class_<add_const_bb,gr::sync_block,
        std::shared_ptr<add_const_bb>>(m, "add_const_bb")

        .def(py::init(&add_const_bb::make),
           py::arg("k") 
        )
        

        .def("k",&add_const_bb::k)
        .def("set_k",&add_const_bb::set_k,
            py::arg("k") 
        )
        .def("to_basic_block",[](std::shared_ptr<add_const_bb> p){
            return p->to_basic_block();
        })
        ;


} 
