

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_CHECK_LFSR_32K_S_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_CHECK_LFSR_32K_S_PYTHON_HPP

#include <gnuradio/blocks/check_lfsr_32k_s.h>

void bind_check_lfsr_32k_s(py::module& m)
{
    using check_lfsr_32k_s    = gr::blocks::check_lfsr_32k_s;


    py::class_<check_lfsr_32k_s,  sync_block,
        std::shared_ptr<check_lfsr_32k_s>>(m, "check_lfsr_32k_s")

        .def(py::init(&check_lfsr_32k_s::make)
        )
        

        .def("ntotal",&check_lfsr_32k_s::ntotal)
        .def("nright",&check_lfsr_32k_s::nright)
        .def("runlength",&check_lfsr_32k_s::runlength)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_CHECK_LFSR_32K_S_PYTHON_HPP */
