/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/complex_to_interleaved_short.h>

void bind_complex_to_interleaved_short(py::module& m)
{
    using complex_to_interleaved_short    = gr::blocks::complex_to_interleaved_short;


    py::class_<complex_to_interleaved_short,gr::sync_interpolator,
        std::shared_ptr<complex_to_interleaved_short>>(m, "complex_to_interleaved_short")

        .def(py::init(&complex_to_interleaved_short::make),
           py::arg("vector") = false 
        )
        

        .def("to_basic_block",[](std::shared_ptr<complex_to_interleaved_short> p){
            return p->to_basic_block();
        })
        ;


} 
