/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/complex_to_arg.h>

void bind_complex_to_arg(py::module& m)
{
    using complex_to_arg    = gr::blocks::complex_to_arg;


    py::class_<complex_to_arg,gr::sync_block,
        std::shared_ptr<complex_to_arg>>(m, "complex_to_arg")

        .def(py::init(&complex_to_arg::make),
           py::arg("vlen") = 1 
        )
        

        .def("to_basic_block",[](std::shared_ptr<complex_to_arg> p){
            return p->to_basic_block();
        })
        ;


} 
