/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/complex_to_mag_squared.h>

void bind_complex_to_mag_squared(py::module& m)
{
    using complex_to_mag_squared    = gr::blocks::complex_to_mag_squared;


    py::class_<complex_to_mag_squared,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<complex_to_mag_squared>>(m, "complex_to_mag_squared")

        .def(py::init(&complex_to_mag_squared::make),
           py::arg("vlen") = 1 
        )
        ;


} 
