/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/complex_to_float.h>

void bind_complex_to_float(py::module& m)
{
    using complex_to_float    = gr::blocks::complex_to_float;


    py::class_<complex_to_float,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<complex_to_float>>(m, "complex_to_float")

        .def(py::init(&complex_to_float::make),
           py::arg("vlen") = 1 
        )
        ;


} 
