/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/count_bits.h>

void bind_count_bits(py::module& m)
{


    m.def("count_bits8",&gr::blocks::count_bits8,
        py::arg("x") 
    );
    m.def("count_bits16",&gr::blocks::count_bits16,
        py::arg("x") 
    );
    m.def("count_bits32",&gr::blocks::count_bits32,
        py::arg("x") 
    );
    m.def("count_bits64",&gr::blocks::count_bits64,
        py::arg("x") 
    );
} 
