/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/ctrlport_probe2_i.h>

void bind_ctrlport_probe2_i(py::module& m)
{
    using ctrlport_probe2_i    = gr::blocks::ctrlport_probe2_i;


    py::class_<ctrlport_probe2_i,gr::sync_block,
        std::shared_ptr<ctrlport_probe2_i>>(m, "ctrlport_probe2_i")

        .def(py::init(&ctrlport_probe2_i::make),
           py::arg("id"), 
           py::arg("desc"), 
           py::arg("len"), 
           py::arg("disp_mask") 
        )
        

        .def("get",&ctrlport_probe2_i::get)
        .def("set_length",&ctrlport_probe2_i::set_length,
            py::arg("len") 
        )
        .def("to_basic_block",[](std::shared_ptr<ctrlport_probe2_i> p){
            return p->to_basic_block();
        })
        ;


} 
