/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/endian_swap.h>

void bind_endian_swap(py::module& m)
{
    using endian_swap    = gr::blocks::endian_swap;


    py::class_<endian_swap,gr::sync_block,
        std::shared_ptr<endian_swap>>(m, "endian_swap")

        .def(py::init(&endian_swap::make),
           py::arg("item_size_bytes") = 1 
        )
        

        .def("to_basic_block",[](std::shared_ptr<endian_swap> p){
            return p->to_basic_block();
        })
        ;


} 
