/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/exponentiate_const_cci.h>

void bind_exponentiate_const_cci(py::module& m)
{
    using exponentiate_const_cci    = gr::blocks::exponentiate_const_cci;


    py::class_<exponentiate_const_cci,gr::sync_block,
        std::shared_ptr<exponentiate_const_cci>>(m, "exponentiate_const_cci")

        .def(py::init(&exponentiate_const_cci::make),
           py::arg("exponent"), 
           py::arg("vlen") = 1 
        )
        

        .def("set_exponent",&exponentiate_const_cci::set_exponent,
            py::arg("exponent") 
        )
        .def("to_basic_block",[](std::shared_ptr<exponentiate_const_cci> p){
            return p->to_basic_block();
        })
        ;


} 
