/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/file_meta_sink.h>

void bind_file_meta_sink(py::module& m)
{
    using file_meta_sink    = gr::blocks::file_meta_sink;

    py::enum_<gr::blocks::gr_file_types>(m,"gr_file_types")
        .value("GR_FILE_BYTE", gr::blocks::GR_FILE_BYTE) // 0
        .value("GR_FILE_CHAR", gr::blocks::GR_FILE_CHAR) // 0
        .value("GR_FILE_SHORT", gr::blocks::GR_FILE_SHORT) // 1
        .value("GR_FILE_INT", gr::blocks::GR_FILE_INT) // 2
        .value("GR_FILE_LONG", gr::blocks::GR_FILE_LONG) // 3
        .value("GR_FILE_LONG_LONG", gr::blocks::GR_FILE_LONG_LONG) // 4
        .value("GR_FILE_FLOAT", gr::blocks::GR_FILE_FLOAT) // 5
        .value("GR_FILE_DOUBLE", gr::blocks::GR_FILE_DOUBLE) // 6
        .export_values()
    ;

    py::class_<file_meta_sink,gr::sync_block,
        std::shared_ptr<file_meta_sink>>(m, "file_meta_sink")

        .def(py::init(&file_meta_sink::make),
           py::arg("itemsize"), 
           py::arg("filename"), 
           py::arg("samp_rate") = 1, 
           py::arg("relative_rate") = 1, 
           py::arg("type") = ::gr::blocks::GR_FILE_FLOAT, 
           py::arg("complex") = true, 
           py::arg("max_segment_size") = 1000000, 
           py::arg("extra_dict") = pmt::make_dict(), 
           py::arg("detached_header") = false 
        )
        

        .def("open",&file_meta_sink::open,
            py::arg("filename") 
        )
        .def("close",&file_meta_sink::close)
        .def("do_update",&file_meta_sink::do_update)
        .def("set_unbuffered",&file_meta_sink::set_unbuffered,
            py::arg("unbuffered") 
        )
        .def("to_basic_block",[](std::shared_ptr<file_meta_sink> p){
            return p->to_basic_block();
        })
        ;

        m.attr("METADATA_VERSION") = gr::blocks::METADATA_VERSION;
        m.attr("METADATA_HEADER_SIZE") = gr::blocks::METADATA_HEADER_SIZE;
} 

