/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/file_sink_base.h>

void bind_file_sink_base(py::module& m)
{
    using file_sink_base    = gr::blocks::file_sink_base;


    py::class_<file_sink_base,
        std::shared_ptr<file_sink_base>>(m, "file_sink_base")

        .def(py::init<>())

        .def("open",&file_sink_base::open,
            py::arg("filename") 
        )
        .def("close",&file_sink_base::close)
        .def("do_update",&file_sink_base::do_update)
        .def("set_unbuffered",&file_sink_base::set_unbuffered,
            py::arg("unbuffered") 
        )
        ;


} 
