/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/file_meta_source.h>

void bind_file_meta_source(py::module& m)
{
    using file_meta_source    = gr::blocks::file_meta_source;


    py::class_<file_meta_source,gr::sync_block,
        std::shared_ptr<file_meta_source>>(m, "file_meta_source")

        .def(py::init(&file_meta_source::make),
           py::arg("filename"), 
           py::arg("repeat") = false, 
           py::arg("detached_header") = false, 
           py::arg("hdr_filename") = "" 
        )
        

        .def("open",&file_meta_source::open,
            py::arg("filename"), 
            py::arg("hdr_filename") = "" 
        )
        .def("close",&file_meta_source::close)
        .def("do_update",&file_meta_source::do_update)
        .def("to_basic_block",[](std::shared_ptr<file_meta_source> p){
            return p->to_basic_block();
        })
        ;


} 
