/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/head.h>

void bind_head(py::module& m)
{
    using head    = gr::blocks::head;


    py::class_<head,gr::sync_block,
        std::shared_ptr<head>>(m, "head")

        .def(py::init(&head::make),
           py::arg("sizeof_stream_item"), 
           py::arg("nitems") 
        )
        

        .def("reset",&head::reset)
        .def("set_length",&head::set_length,
            py::arg("nitems") 
        )
        .def("to_basic_block",[](std::shared_ptr<head> p){
            return p->to_basic_block();
        })
        ;


} 
