

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_LOG2_CONST_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_LOG2_CONST_PYTHON_HPP

#include <gnuradio/blocks/log2_const.h>

void bind_log2_const(py::module& m)
{


    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
    m.def("log2_const",&gr::blocks::log2_const);
} 

#endif /* INCLUDED_GR_BLOCKS_LOG2_CONST_PYTHON_HPP */
