/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/message_strobe.h>

void bind_message_strobe(py::module& m)
{
    using message_strobe    = gr::blocks::message_strobe;


    py::class_<message_strobe,gr::block,
        std::shared_ptr<message_strobe>>(m, "message_strobe")

        .def(py::init(&message_strobe::make),
           py::arg("msg"), 
           py::arg("period_ms") 
        )
        

        .def("set_msg",&message_strobe::set_msg,
            py::arg("msg") 
        )
        .def("msg",&message_strobe::msg)
        .def("set_period",&message_strobe::set_period,
            py::arg("period_ms") 
        )
        .def("period",&message_strobe::period)
        .def("to_basic_block",[](std::shared_ptr<message_strobe> p){
            return p->to_basic_block();
        })
        ;


} 
