/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/message_strobe_random.h>

void bind_message_strobe_random(py::module& m)
{
    using message_strobe_random    = gr::blocks::message_strobe_random;


    py::class_<message_strobe_random,gr::block,
        std::shared_ptr<message_strobe_random>>(m, "message_strobe_random")

        .def(py::init(&message_strobe_random::make),
           py::arg("msg"), 
           py::arg("dist"), 
           py::arg("mean_ms"), 
           py::arg("std_ms") 
        )
        

        .def("set_msg",&message_strobe_random::set_msg,
            py::arg("msg") 
        )
        .def("msg",&message_strobe_random::msg)
        .def("set_dist",&message_strobe_random::set_dist,
            py::arg("dist") 
        )
        .def("dist",&message_strobe_random::dist)
        .def("set_mean",&message_strobe_random::set_mean,
            py::arg("mean") 
        )
        .def("mean",&message_strobe_random::mean)
        .def("set_std",&message_strobe_random::set_std,
            py::arg("std") 
        )
        .def("std",&message_strobe_random::std)
        .def("to_basic_block",[](std::shared_ptr<message_strobe_random> p){
            return p->to_basic_block();
        })
        ;

    py::enum_<gr::blocks::message_strobe_random_distribution_t>(m,"message_strobe_random_distribution_t")
        .value("STROBE_POISSON", gr::blocks::STROBE_POISSON) // 1
        .value("STROBE_GAUSSIAN", gr::blocks::STROBE_GAUSSIAN) // 2
        .value("STROBE_UNIFORM", gr::blocks::STROBE_UNIFORM) // 3
        .export_values()
    ;

} 
