/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/multiply_conjugate_cc.h>

void bind_multiply_conjugate_cc(py::module& m)
{
    using multiply_conjugate_cc    = gr::blocks::multiply_conjugate_cc;


    py::class_<multiply_conjugate_cc,gr::sync_block,
        std::shared_ptr<multiply_conjugate_cc>>(m, "multiply_conjugate_cc")

        .def(py::init(&multiply_conjugate_cc::make),
           py::arg("vlen") = 1 
        )
        

        .def("to_basic_block",[](std::shared_ptr<multiply_conjugate_cc> p){
            return p->to_basic_block();
        })
        ;


} 
