/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/nlog10_ff.h>

void bind_nlog10_ff(py::module& m)
{
    using nlog10_ff    = gr::blocks::nlog10_ff;


    py::class_<nlog10_ff,gr::sync_block,
        std::shared_ptr<nlog10_ff>>(m, "nlog10_ff")

        .def(py::init(&nlog10_ff::make),
           py::arg("n") = 1., 
           py::arg("vlen") = 1, 
           py::arg("k") = 0. 
        )
        

        .def("to_basic_block",[](std::shared_ptr<nlog10_ff> p){
            return p->to_basic_block();
        })
        ;


} 
