/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/null_source.h>

void bind_null_source(py::module& m)
{
    using null_source    = gr::blocks::null_source;


    py::class_<null_source,gr::sync_block,
        std::shared_ptr<null_source>>(m, "null_source")

        .def(py::init(&null_source::make),
           py::arg("sizeof_stream_item") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<null_source> p){
            return p->to_basic_block();
        })
        ;


} 
