/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/pack_k_bits.h>

void bind_pack_k_bits(py::module& m)
{
    using pack_k_bits    = gr::blocks::kernel::pack_k_bits;


    py::class_<pack_k_bits,
        std::shared_ptr<pack_k_bits>>(m, "pack_k_bits")

        .def(py::init<unsigned int>(),           py::arg("k") 
        )
        .def(py::init<gr::blocks::kernel::pack_k_bits const &>(),           py::arg("arg0") 
        )

        .def("pack",&pack_k_bits::pack,
            py::arg("bytes"), 
            py::arg("bits"), 
            py::arg("nbytes") 
        )
        .def("pack_rev",&pack_k_bits::pack_rev,
            py::arg("bytes"), 
            py::arg("bits"), 
            py::arg("nbytes") 
        )
        .def("k",&pack_k_bits::k)
        ;


} 
