/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/pdu.h>

void bind_pdu(py::module& m)
{

    py::enum_<gr::blocks::pdu::vector_type>(m,"vector_type")
        .value("byte_t", gr::blocks::pdu::byte_t) // 0
        .value("float_t", gr::blocks::pdu::float_t) // 1
        .value("complex_t", gr::blocks::pdu::complex_t) // 2
        .export_values()
    ;

    m.def("pdu_port_id",&gr::blocks::pdu::pdu_port_id);
    m.def("itemsize",&gr::blocks::pdu::itemsize,
        py::arg("type") 
    );
    m.def("type_matches",&gr::blocks::pdu::type_matches,
        py::arg("type"), 
        py::arg("v") 
    );
    m.def("make_pdu_vector",&gr::blocks::pdu::make_pdu_vector,
        py::arg("type"), 
        py::arg("buf"), 
        py::arg("items") 
    );
    m.def("type_from_pmt",&gr::blocks::pdu::type_from_pmt,
        py::arg("vector") 
    );
} 
