

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_PDU_SET_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_PDU_SET_PYTHON_HPP

#include <gnuradio/blocks/pdu_set.h>

void bind_pdu_set(py::module& m)
{
    using pdu_set    = gr::blocks::pdu_set;


    py::class_<pdu_set,  block,
        std::shared_ptr<pdu_set>>(m, "pdu_set")

        .def(py::init(&pdu_set::make),
           py::arg("k"), 
           py::arg("v") 
        )
        

        .def("set_key",&pdu_set::set_key,
            py::arg("key") 
        )
        .def("set_val",&pdu_set::set_val,
            py::arg("val") 
        )

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_PDU_SET_PYTHON_HPP */
