/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/peak_detector2_fb.h>

void bind_peak_detector2_fb(py::module& m)
{
    using peak_detector2_fb    = gr::blocks::peak_detector2_fb;


    py::class_<peak_detector2_fb,gr::sync_block,
        std::shared_ptr<peak_detector2_fb>>(m, "peak_detector2_fb")

        .def(py::init(&peak_detector2_fb::make),
           py::arg("threshold_factor_rise") = 7, 
           py::arg("look_ahead") = 1000, 
           py::arg("alpha") = 0.001 
        )
        

        .def("set_threshold_factor_rise",&peak_detector2_fb::set_threshold_factor_rise,
            py::arg("thr") 
        )
        .def("set_look_ahead",&peak_detector2_fb::set_look_ahead,
            py::arg("look") 
        )
        .def("set_alpha",&peak_detector2_fb::set_alpha,
            py::arg("alpha") 
        )
        .def("threshold_factor_rise",&peak_detector2_fb::threshold_factor_rise)
        .def("look_ahead",&peak_detector2_fb::look_ahead)
        .def("alpha",&peak_detector2_fb::alpha)
        .def("to_basic_block",[](std::shared_ptr<peak_detector2_fb> p){
            return p->to_basic_block();
        })
        ;


} 
