

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_PEAK_DETECTOR2_FB_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_PEAK_DETECTOR2_FB_PYTHON_HPP

#include <gnuradio/blocks/peak_detector2_fb.h>

void bind_peak_detector2_fb(py::module& m)
{
    using peak_detector2_fb    = gr::blocks::peak_detector2_fb;


    py::class_<peak_detector2_fb,  sync_block,
        std::shared_ptr<peak_detector2_fb>>(m, "peak_detector2_fb")

        .def(py::init(&peak_detector2_fb::make),
           py::arg("threshold_factor_rise") = 7, 
           py::arg("look_ahead") = 1000, 
           py::arg("alpha") = 0.001 
        )
        

        .def("set_threshold_factor_rise",&peak_detector2_fb::set_threshold_factor_rise,
            py::arg("thr") 
        )
        .def("set_look_ahead",&peak_detector2_fb::set_look_ahead,
            py::arg("look") 
        )
        .def("set_alpha",&peak_detector2_fb::set_alpha,
            py::arg("alpha") 
        )
        .def("threshold_factor_rise",&peak_detector2_fb::threshold_factor_rise)
        .def("look_ahead",&peak_detector2_fb::look_ahead)
        .def("alpha",&peak_detector2_fb::alpha)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_PEAK_DETECTOR2_FB_PYTHON_HPP */
