/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/probe_rate.h>

void bind_probe_rate(py::module& m)
{
    using probe_rate    = gr::blocks::probe_rate;


    py::class_<probe_rate,gr::sync_block,
        std::shared_ptr<probe_rate>>(m, "probe_rate")

        .def(py::init(&probe_rate::make),
           py::arg("itemsize"), 
           py::arg("update_rate_ms") = 500., 
           py::arg("alpha") = 1.0E-4 
        )
        

        .def("set_alpha",&probe_rate::set_alpha,
            py::arg("alpha") 
        )
        .def("rate",&probe_rate::rate)
        .def("start",&probe_rate::start)
        .def("stop",&probe_rate::stop)
        .def("to_basic_block",[](std::shared_ptr<probe_rate> p){
            return p->to_basic_block();
        })
        ;


} 
