/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/regenerate_bb.h>

void bind_regenerate_bb(py::module& m)
{
    using regenerate_bb    = gr::blocks::regenerate_bb;


    py::class_<regenerate_bb,gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<regenerate_bb>>(m, "regenerate_bb")

        .def(py::init(&regenerate_bb::make),
           py::arg("period"), 
           py::arg("max_regen") = 500 
        )
        

        .def("set_max_regen",&regenerate_bb::set_max_regen,
            py::arg("regen") 
        )
        .def("set_period",&regenerate_bb::set_period,
            py::arg("period") 
        )
        .def("max_regen",&regenerate_bb::max_regen)
        .def("period",&regenerate_bb::period)
        ;


} 
