/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/rotator_cc.h>

void bind_rotator_cc(py::module& m)
{
    using rotator_cc    = gr::blocks::rotator_cc;


    py::class_<rotator_cc,gr::sync_block,
        std::shared_ptr<rotator_cc>>(m, "rotator_cc")

        .def(py::init(&rotator_cc::make),
           py::arg("phase_inc") = 0. 
        )
        

        .def("set_phase_inc",&rotator_cc::set_phase_inc,
            py::arg("phase_inc") 
        )
        .def("to_basic_block",[](std::shared_ptr<rotator_cc> p){
            return p->to_basic_block();
        })
        ;


} 
