

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_SELECTOR_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_SELECTOR_PYTHON_HPP

#include <gnuradio/blocks/selector.h>

void bind_selector(py::module& m)
{
    using selector    = gr::blocks::selector;


    py::class_<selector,  block,
        std::shared_ptr<selector>>(m, "selector")

        .def(py::init(&selector::make),
           py::arg("itemsize"), 
           py::arg("input_index"), 
           py::arg("output_index") 
        )
        

        .def("set_enabled",&selector::set_enabled,
            py::arg("enable") 
        )
        .def("enabled",&selector::enabled)
        .def("set_input_index",&selector::set_input_index,
            py::arg("input_index") 
        )
        .def("input_index",&selector::input_index)
        .def("set_output_index",&selector::set_output_index,
            py::arg("output_index") 
        )
        .def("output_index",&selector::output_index)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_SELECTOR_PYTHON_HPP */
