/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/short_to_float.h>

void bind_short_to_float(py::module& m)
{
    using short_to_float    = gr::blocks::short_to_float;


    py::class_<short_to_float,gr::sync_block,
        std::shared_ptr<short_to_float>>(m, "short_to_float")

        .def(py::init(&short_to_float::make),
           py::arg("vlen") = 1, 
           py::arg("scale") = 1. 
        )
        

        .def("scale",&short_to_float::scale)
        .def("set_scale",&short_to_float::set_scale,
            py::arg("scale") 
        )
        .def("to_basic_block",[](std::shared_ptr<short_to_float> p){
            return p->to_basic_block();
        })
        ;


} 
