/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/stream_mux.h>

void bind_stream_mux(py::module& m)
{
    using stream_mux    = gr::blocks::stream_mux;


    py::class_<stream_mux,gr::block,
        std::shared_ptr<stream_mux>>(m, "stream_mux")

        .def(py::init(&stream_mux::make),
           py::arg("itemsize"), 
           py::arg("lengths") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<stream_mux> p){
            return p->to_basic_block();
        })
        ;


} 
