/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/tagged_stream_multiply_length.h>

void bind_tagged_stream_multiply_length(py::module& m)
{
    using tagged_stream_multiply_length    = gr::blocks::tagged_stream_multiply_length;


    py::class_<tagged_stream_multiply_length,gr::block,
        std::shared_ptr<tagged_stream_multiply_length>>(m, "tagged_stream_multiply_length")

        .def(py::init(&tagged_stream_multiply_length::make),
           py::arg("itemsize"), 
           py::arg("lengthtagname"), 
           py::arg("scalar") 
        )
        

        .def("set_scalar",&tagged_stream_multiply_length::set_scalar,
            py::arg("scalar") 
        )
        .def("to_basic_block",[](std::shared_ptr<tagged_stream_multiply_length> p){
            return p->to_basic_block();
        })
        ;


} 
