/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/tagged_stream_to_pdu.h>

void bind_tagged_stream_to_pdu(py::module& m)
{
    using tagged_stream_to_pdu    = gr::blocks::tagged_stream_to_pdu;


    py::class_<tagged_stream_to_pdu,gr::tagged_stream_block,
        std::shared_ptr<tagged_stream_to_pdu>>(m, "tagged_stream_to_pdu")

        .def(py::init(&tagged_stream_to_pdu::make),
           py::arg("type"), 
           py::arg("lengthtagname") = "packet_len" 
        )
        

        .def("to_basic_block",[](std::shared_ptr<tagged_stream_to_pdu> p){
            return p->to_basic_block();
        })
        ;


} 
