

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_TAGS_STROBE_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_TAGS_STROBE_PYTHON_HPP

#include <gnuradio/blocks/tags_strobe.h>

void bind_tags_strobe(py::module& m)
{
    using tags_strobe    = gr::blocks::tags_strobe;


    py::class_<tags_strobe,  sync_block,
        std::shared_ptr<tags_strobe>>(m, "tags_strobe")

        .def(py::init(&tags_strobe::make),
           py::arg("sizeof_stream_item"), 
           py::arg("value"), 
           py::arg("nsamps"), 
           py::arg("key") = pmt::intern("strobe") 
        )
        

        .def("set_value",&tags_strobe::set_value,
            py::arg("value") 
        )
        .def("set_key",&tags_strobe::set_key,
            py::arg("key") 
        )
        .def("value",&tags_strobe::value)
        .def("key",&tags_strobe::key)
        .def("set_nsamps",&tags_strobe::set_nsamps,
            py::arg("nsamps") 
        )
        .def("nsamps",&tags_strobe::nsamps)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_TAGS_STROBE_PYTHON_HPP */
