/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/test_tag_variable_rate_ff.h>

void bind_test_tag_variable_rate_ff(py::module& m)
{
    using test_tag_variable_rate_ff    = gr::blocks::test_tag_variable_rate_ff;


    py::class_<test_tag_variable_rate_ff,gr::block,
        std::shared_ptr<test_tag_variable_rate_ff>>(m, "test_tag_variable_rate_ff")

        .def(py::init(&test_tag_variable_rate_ff::make),
           py::arg("update_once") = false, 
           py::arg("update_step") = 0.001 
        )
        

        .def("to_basic_block",[](std::shared_ptr<test_tag_variable_rate_ff> p){
            return p->to_basic_block();
        })
        ;


} 
