/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/tuntap_pdu.h>

void bind_tuntap_pdu(py::module& m)
{
    using tuntap_pdu    = gr::blocks::tuntap_pdu;


    py::class_<tuntap_pdu,gr::block,
        std::shared_ptr<tuntap_pdu>>(m, "tuntap_pdu")

        .def(py::init(&tuntap_pdu::make),
           py::arg("dev"), 
           py::arg("MTU") = 10000, 
           py::arg("istunflag") = false 
        )
        

        .def("to_basic_block",[](std::shared_ptr<tuntap_pdu> p){
            return p->to_basic_block();
        })
        ;


} 
