/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/udp_source.h>

void bind_udp_source(py::module& m)
{
    using udp_source    = gr::blocks::udp_source;


    py::class_<udp_source,gr::sync_block,
        std::shared_ptr<udp_source>>(m, "udp_source")

        .def(py::init(&udp_source::make),
           py::arg("itemsize"), 
           py::arg("host"), 
           py::arg("port"), 
           py::arg("payload_size") = 1472, 
           py::arg("eof") = true 
        )
        

        .def("connect",&udp_source::connect,
            py::arg("host"), 
            py::arg("port") 
        )
        .def("disconnect",&udp_source::disconnect)
        .def("payload_size",&udp_source::payload_size)
        .def("get_port",&udp_source::get_port)
        .def("to_basic_block",[](std::shared_ptr<udp_source> p){
            return p->to_basic_block();
        })
        ;


} 
