

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_UDP_SOURCE_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_UDP_SOURCE_PYTHON_HPP

#include <gnuradio/blocks/udp_source.h>

void bind_udp_source(py::module& m)
{
    using udp_source    = gr::blocks::udp_source;


    py::class_<udp_source,  sync_block,
        std::shared_ptr<udp_source>>(m, "udp_source")

        .def(py::init(&udp_source::make),
           py::arg("itemsize"), 
           py::arg("host"), 
           py::arg("port"), 
           py::arg("payload_size") = 1472, 
           py::arg("eof") = true 
        )
        

        .def("connect",&udp_source::connect,
            py::arg("host"), 
            py::arg("port") 
        )
        .def("disconnect",&udp_source::disconnect)
        .def("payload_size",&udp_source::payload_size)
        .def("get_port",&udp_source::get_port)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_UDP_SOURCE_PYTHON_HPP */
