/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/vector_map.h>

void bind_vector_map(py::module& m)
{
    using vector_map    = gr::blocks::vector_map;


    py::class_<vector_map,gr::sync_block,
        std::shared_ptr<vector_map>>(m, "vector_map")

        .def(py::init(&vector_map::make),
           py::arg("item_size"), 
           py::arg("in_vlens"), 
           py::arg("mapping") 
        )
        

        .def("set_mapping",&vector_map::set_mapping,
            py::arg("mapping") 
        )
        .def("to_basic_block",[](std::shared_ptr<vector_map> p){
            return p->to_basic_block();
        })
        ;


} 
