/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/wavfile_source.h>

void bind_wavfile_source(py::module& m)
{
    using wavfile_source    = gr::blocks::wavfile_source;


    py::class_<wavfile_source,gr::sync_block,
        std::shared_ptr<wavfile_source>>(m, "wavfile_source")

        .def(py::init(&wavfile_source::make),
           py::arg("filename"), 
           py::arg("repeat") = false 
        )
        

        .def("sample_rate",&wavfile_source::sample_rate)
        .def("bits_per_sample",&wavfile_source::bits_per_sample)
        .def("channels",&wavfile_source::channels)
        .def("to_basic_block",[](std::shared_ptr<wavfile_source> p){
            return p->to_basic_block();
        })
        ;


} 
