/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/wavfile.h>

void bind_wavfile(py::module& m)
{


    m.def("wavheader_parse",&gr::blocks::wavheader_parse,
        py::arg("fp"), 
        py::arg("sample_rate"), 
        py::arg("nchans"), 
        py::arg("bytes_per_sample"), 
        py::arg("first_sample_pos"), 
        py::arg("samples_per_chan") 
    );
    m.def("wav_read_sample",&gr::blocks::wav_read_sample,
        py::arg("fp"), 
        py::arg("bytes_per_sample") 
    );
    m.def("wavheader_write",&gr::blocks::wavheader_write,
        py::arg("fp"), 
        py::arg("sample_rate"), 
        py::arg("nchans"), 
        py::arg("bytes_per_sample") 
    );
    m.def("wav_write_sample",&gr::blocks::wav_write_sample,
        py::arg("fp"), 
        py::arg("sample"), 
        py::arg("bytes_per_sample") 
    );
    m.def("wavheader_complete",&gr::blocks::wavheader_complete,
        py::arg("fp"), 
        py::arg("byte_count") 
    );
} 
