

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BLOCKS_WAVFILE_SOURCE_PYTHON_HPP
#define INCLUDED_GR_BLOCKS_WAVFILE_SOURCE_PYTHON_HPP

#include <gnuradio/blocks/wavfile_source.h>

void bind_wavfile_source(py::module& m)
{
    using wavfile_source    = gr::blocks::wavfile_source;


    py::class_<wavfile_source,  sync_block,
        std::shared_ptr<wavfile_source>>(m, "wavfile_source")

        .def(py::init(&wavfile_source::make),
           py::arg("filename"), 
           py::arg("repeat") = false 
        )
        

        .def("sample_rate",&wavfile_source::sample_rate)
        .def("bits_per_sample",&wavfile_source::bits_per_sample)
        .def("channels",&wavfile_source::channels)

        ;


} 

#endif /* INCLUDED_GR_BLOCKS_WAVFILE_SOURCE_PYTHON_HPP */
