/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/audio/source.h>

void bind_source(py::module& m)
{
    using source    = gr::audio::source;


    py::class_<source,gr::sync_block,
        std::shared_ptr<source>>(m, "source")

        .def(py::init(&source::make),
           py::arg("sampling_rate"), 
           py::arg("device_name") = "", 
           py::arg("ok_to_block") = true 
        )
        

        .def("to_basic_block",[](std::shared_ptr<source> p){
            return p->to_basic_block();
        })
        ;


} 
