/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/trellis/base.h>

void bind_base(py::module& m)
{


    m.def("dec2base",&gr::trellis::dec2base,
        py::arg("num"), 
        py::arg("base"), 
        py::arg("s") 
    );
    m.def("dec2bases",&gr::trellis::dec2bases,
        py::arg("num"), 
        py::arg("bases"), 
        py::arg("s") 
    );
    m.def("base2dec",&gr::trellis::base2dec,
        py::arg("s"), 
        py::arg("base") 
    );
    m.def("bases2dec",&gr::trellis::bases2dec,
        py::arg("s"), 
        py::arg("bases") 
    );
} 
