/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/trellis/siso_f.h>

void bind_siso_f(py::module& m)
{
    using siso_f    = gr::trellis::siso_f;


    py::class_<siso_f,gr::block,
        std::shared_ptr<siso_f>>(m, "siso_f")

        .def(py::init(&siso_f::make),
           py::arg("FSM"), 
           py::arg("K"), 
           py::arg("S0"), 
           py::arg("SK"), 
           py::arg("POSTI"), 
           py::arg("POSTO"), 
           py::arg("d_SISO_TYPE") 
        )
        

        .def("FSM",&siso_f::FSM)
        .def("K",&siso_f::K)
        .def("S0",&siso_f::S0)
        .def("SK",&siso_f::SK)
        .def("POSTI",&siso_f::POSTI)
        .def("POSTO",&siso_f::POSTO)
        .def("SISO_TYPE",&siso_f::SISO_TYPE)
        .def("set_FSM",&siso_f::set_FSM,
            py::arg("FSM") 
        )
        .def("set_K",&siso_f::set_K,
            py::arg("K") 
        )
        .def("set_S0",&siso_f::set_S0,
            py::arg("S0") 
        )
        .def("set_SK",&siso_f::set_SK,
            py::arg("SK") 
        )
        .def("set_POSTI",&siso_f::set_POSTI,
            py::arg("posti") 
        )
        .def("set_POSTO",&siso_f::set_POSTO,
            py::arg("posto") 
        )
        .def("set_SISO_TYPE",&siso_f::set_SISO_TYPE,
            py::arg("type") 
        )
        .def("to_basic_block",[](std::shared_ptr<siso_f> p){
            return p->to_basic_block();
        })
        ;


} 
