/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/ber_bf.h>

void bind_ber_bf(py::module& m)
{
    using ber_bf    = gr::fec::ber_bf;


    py::class_<ber_bf,gr::block,
        std::shared_ptr<ber_bf>>(m, "ber_bf")

        .def(py::init(&ber_bf::make),
           py::arg("test_mode") = false, 
           py::arg("berminerrors") = 100, 
           py::arg("ber_limit") = -7. 
        )
        

        .def("total_errors",&ber_bf::total_errors)
        .def("to_basic_block",[](std::shared_ptr<ber_bf> p){
            return p->to_basic_block();
        })
        ;


} 
