/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/cc_encoder.h>

void bind_cc_encoder(py::module& m)
{
    using cc_encoder    = gr::fec::code::cc_encoder;


    py::class_<cc_encoder,gr::fec::generic_encoder,
        std::shared_ptr<cc_encoder>>(m, "cc_encoder")

        // .def(py::init(&cc_encoder::make),
        //    py::arg("frame_size"), 
        //    py::arg("k"), 
        //    py::arg("rate"), 
        //    py::arg("polys"), 
        //    py::arg("start_state") = 0, 
        //    py::arg("mode") = ::_cc_mode_t::CC_STREAMING, 
        //    py::arg("padded") = false 
        // )
        
        .def_static("make",&cc_encoder::make,
           py::arg("frame_size"), 
           py::arg("k"), 
           py::arg("rate"), 
           py::arg("polys"), 
           py::arg("start_state") = 0, 
           py::arg("mode") = ::_cc_mode_t::CC_STREAMING, 
           py::arg("padded") = false 
        )

        .def("set_frame_size",&cc_encoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("rate",&cc_encoder::rate)
        ;


} 
