/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/dummy_encoder.h>

void bind_dummy_encoder(py::module& m)
{
    using dummy_encoder    = gr::fec::code::dummy_encoder;


    py::class_<dummy_encoder,gr::fec::generic_encoder,
        std::shared_ptr<dummy_encoder>>(m, "dummy_encoder")

        // .def(py::init(&dummy_encoder::make),
        //    py::arg("frame_size"), 
        //    py::arg("pack") = false, 
        //    py::arg("packed_bits") = false 
        // )
        
        .def_static("make",&dummy_encoder::make,
           py::arg("frame_size"), 
           py::arg("pack") = false, 
           py::arg("packed_bits") = false 
        )
        

        .def("set_frame_size",&dummy_encoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("rate",&dummy_encoder::rate)
        ;


} 
