/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/dummy_decoder.h>

void bind_dummy_decoder(py::module& m)
{
    using dummy_decoder    = gr::fec::code::dummy_decoder;


    py::class_<dummy_decoder,gr::fec::generic_decoder,
        std::shared_ptr<dummy_decoder>>(m, "dummy_decoder")

        // .def(py::init(&dummy_decoder::make),
        //    py::arg("frame_size") 
        // )
        
        .def_static("make",&dummy_decoder::make,
           py::arg("frame_size") 
        )

        .def("set_frame_size",&dummy_decoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("rate",&dummy_decoder::rate)
        ;


} 
