/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/generic_encoder.h>

void bind_generic_encoder(py::module& m)
{
    using generic_encoder    = gr::fec::generic_encoder;


    py::class_<generic_encoder,
        std::shared_ptr<generic_encoder>>(m, "generic_encoder")

        .def("generic_work",&generic_encoder::generic_work,
            py::arg("in_buffer"), 
            py::arg("out_buffer") 
        )
        .def("unique_id",&generic_encoder::unique_id)
        .def("alias",&generic_encoder::alias)
        .def("rate",&generic_encoder::rate)
        .def("get_input_size",&generic_encoder::get_input_size)
        .def("get_output_size",&generic_encoder::get_output_size)
        .def("get_input_conversion",&generic_encoder::get_input_conversion)
        .def("get_output_conversion",&generic_encoder::get_output_conversion)
        .def("set_frame_size",&generic_encoder::set_frame_size,
            py::arg("frame_size") 
        )
        ;


    m.def("get_encoder_output_size",&gr::fec::get_encoder_output_size,
        py::arg("my_encoder") 
    );
    m.def("get_encoder_input_size",&gr::fec::get_encoder_input_size,
        py::arg("my_encoder") 
    );
    m.def("get_encoder_input_conversion",&gr::fec::get_encoder_input_conversion,
        py::arg("my_encoder") 
    );
    m.def("get_encoder_output_conversion",&gr::fec::get_encoder_output_conversion,
        py::arg("my_encoder") 
    );
} 
