/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/ldpc_G_matrix.h>

void bind_ldpc_G_matrix(py::module& m)
{
    using ldpc_G_matrix    = gr::fec::code::ldpc_G_matrix;


    py::class_<ldpc_G_matrix,gr::fec::code::fec_mtrx,
        std::shared_ptr<ldpc_G_matrix>>(m, "ldpc_G_matrix")

        .def(py::init(&ldpc_G_matrix::make),
           py::arg("filename") 
        )
        

        .def("encode",&ldpc_G_matrix::encode,
            py::arg("outbuffer"), 
            py::arg("inbuffer") 
        )
        .def("decode",&ldpc_G_matrix::decode,
            py::arg("outbuffer"), 
            py::arg("inbuffer"), 
            py::arg("frame_size"), 
            py::arg("max_iterations") 
        )
        .def("get_base_sptr",&ldpc_G_matrix::get_base_sptr)
        ;


} 
