/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/ldpc_bit_flip_decoder.h>

void bind_ldpc_bit_flip_decoder(py::module& m)
{
    using ldpc_bit_flip_decoder    = gr::fec::code::ldpc_bit_flip_decoder;


    py::class_<ldpc_bit_flip_decoder,gr::fec::generic_decoder,
        std::shared_ptr<ldpc_bit_flip_decoder>>(m, "ldpc_bit_flip_decoder")

        // .def(py::init(&ldpc_bit_flip_decoder::make),
        //    py::arg("mtrx_obj"), 
        //    py::arg("max_iter") = 100 
        // )

        .def_static("make",&ldpc_bit_flip_decoder::make,
           py::arg("mtrx_obj"), 
           py::arg("max_iter") = 100 
        )
        

        .def("set_frame_size",&ldpc_bit_flip_decoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("rate",&ldpc_bit_flip_decoder::rate)
        ;


} 
