/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/ldpc_H_matrix.h>

void bind_ldpc_H_matrix(py::module& m)
{
    using ldpc_H_matrix    = gr::fec::code::ldpc_H_matrix;


    py::class_<ldpc_H_matrix,gr::fec::code::fec_mtrx,
        std::shared_ptr<ldpc_H_matrix>>(m, "ldpc_H_matrix")

        .def(py::init(&ldpc_H_matrix::make),
           py::arg("filename"), 
           py::arg("gap") 
        )
        

        .def("encode",&ldpc_H_matrix::encode,
            py::arg("outbuffer"), 
            py::arg("inbuffer") 
        )
        .def("decode",&ldpc_H_matrix::decode,
            py::arg("outbuffer"), 
            py::arg("inbuffer"), 
            py::arg("frame_size"), 
            py::arg("max_iterations") 
        )
        .def("n",&ldpc_H_matrix::n)
        .def("k",&ldpc_H_matrix::k)
        .def("get_base_sptr",&ldpc_H_matrix::get_base_sptr)
        ;


} 
