/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/polar_decoder_sc.h>

void bind_polar_decoder_sc(py::module& m)
{
    using polar_decoder_sc    = gr::fec::code::polar_decoder_sc;


    py::class_<polar_decoder_sc,gr::fec::code::polar_decoder_common,
        std::shared_ptr<polar_decoder_sc>>(m, "polar_decoder_sc")

        // .def(py::init(&polar_decoder_sc::make),
        //    py::arg("block_size"), 
        //    py::arg("num_info_bits"), 
        //    py::arg("frozen_bit_positions"), 
        //    py::arg("frozen_bit_values") 
        // )

        .def_static("make",&polar_decoder_sc::make,
           py::arg("block_size"), 
           py::arg("num_info_bits"), 
           py::arg("frozen_bit_positions"), 
           py::arg("frozen_bit_values") 
        )
        

        .def("generic_work",&polar_decoder_sc::generic_work,
            py::arg("in_buffer"), 
            py::arg("out_buffer") 
        )
        ;


} 
