/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/polar_encoder.h>

void bind_polar_encoder(py::module& m)
{
    using polar_encoder    = gr::fec::code::polar_encoder;


    py::class_<polar_encoder,gr::fec::generic_encoder,
        std::shared_ptr<polar_encoder>>(m, "polar_encoder")

        // .def(py::init(&polar_encoder::make),
        //    py::arg("block_size"), 
        //    py::arg("num_info_bits"), 
        //    py::arg("frozen_bit_positions"), 
        //    py::arg("frozen_bit_values"), 
        //    py::arg("is_packed") = false 
        // )
        .def_static("make",&polar_encoder::make,
           py::arg("block_size"), 
           py::arg("num_info_bits"), 
           py::arg("frozen_bit_positions"), 
           py::arg("frozen_bit_values"), 
           py::arg("is_packed") = false 
        )

        .def("generic_work",&polar_encoder::generic_work,
            py::arg("in_buffer"), 
            py::arg("out_buffer") 
        )
        .def("rate",&polar_encoder::rate)
        .def("get_input_size",&polar_encoder::get_input_size)
        .def("get_output_size",&polar_encoder::get_output_size)
        .def("set_frame_size",&polar_encoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("get_input_conversion",&polar_encoder::get_input_conversion)
        .def("get_output_conversion",&polar_encoder::get_output_conversion)
        ;


} 
