/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/polar_encoder_systematic.h>

void bind_polar_encoder_systematic(py::module& m)
{
    using polar_encoder_systematic    = gr::fec::code::polar_encoder_systematic;


    py::class_<polar_encoder_systematic,gr::fec::generic_encoder,
        std::shared_ptr<polar_encoder_systematic>>(m, "polar_encoder_systematic")

        // .def(py::init(&polar_encoder_systematic::make),
        //    py::arg("block_size"), 
        //    py::arg("num_info_bits"), 
        //    py::arg("frozen_bit_positions") 
        // )
        .def_static("make",&polar_encoder_systematic::make,
           py::arg("block_size"), 
           py::arg("num_info_bits"), 
           py::arg("frozen_bit_positions") 
        )

        .def("generic_work",&polar_encoder_systematic::generic_work,
            py::arg("in_buffer"), 
            py::arg("out_buffer") 
        )
        .def("rate",&polar_encoder_systematic::rate)
        .def("get_input_size",&polar_encoder_systematic::get_input_size)
        .def("get_output_size",&polar_encoder_systematic::get_output_size)
        .def("set_frame_size",&polar_encoder_systematic::set_frame_size,
            py::arg("frame_size") 
        )
        ;


} 
