/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/polar_decoder_common.h>

void bind_polar_decoder_common(py::module& m)
{
    using polar_decoder_common    = gr::fec::code::polar_decoder_common;


    py::class_<polar_decoder_common,gr::fec::generic_decoder,
        std::shared_ptr<polar_decoder_common>>(m, "polar_decoder_common")

        .def("rate",&polar_decoder_common::rate)
        .def("get_input_size",&polar_decoder_common::get_input_size)
        .def("get_output_size",&polar_decoder_common::get_output_size)
        .def("set_frame_size",&polar_decoder_common::set_frame_size,
            py::arg("frame_size") 
        )
        ;


} 
