/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/puncture_ff.h>

void bind_puncture_ff(py::module& m)
{
    using puncture_ff    = gr::fec::puncture_ff;


    py::class_<puncture_ff,gr::block,
        std::shared_ptr<puncture_ff>>(m, "puncture_ff")

        .def(py::init(&puncture_ff::make),
           py::arg("puncsize"), 
           py::arg("puncpat"), 
           py::arg("delay") 
        )
        

        .def("to_basic_block",[](std::shared_ptr<puncture_ff> p){
            return p->to_basic_block();
        })
        ;


} 
