/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/puncture_bb.h>

void bind_puncture_bb(py::module& m)
{
    using puncture_bb    = gr::fec::puncture_bb;


    py::class_<puncture_bb,gr::block,
        std::shared_ptr<puncture_bb>>(m, "puncture_bb")

        .def(py::init(&puncture_bb::make),
           py::arg("puncsize"), 
           py::arg("puncpat"), 
           py::arg("delay") = 0 
        )
        

        .def("to_basic_block",[](std::shared_ptr<puncture_bb> p){
            return p->to_basic_block();
        })
        ;


} 
