/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/repetition_decoder.h>

void bind_repetition_decoder(py::module& m)
{
    using repetition_decoder    = gr::fec::code::repetition_decoder;


    py::class_<repetition_decoder,gr::fec::generic_decoder,
        std::shared_ptr<repetition_decoder>>(m, "repetition_decoder")

        // .def(py::init(&repetition_decoder::make),
        //    py::arg("frame_size"), 
        //    py::arg("rep"), 
        //    py::arg("ap_prob") = 0.5 
        // )
        .def_static("make",&repetition_decoder::make,
           py::arg("frame_size"), 
           py::arg("rep"), 
           py::arg("ap_prob") = 0.5 
        )
        

        .def("set_frame_size",&repetition_decoder::set_frame_size,
            py::arg("frame_size") 
        )
        .def("rate",&repetition_decoder::rate)
        ;


} 
