

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_BUFFER_PYTHON_HPP
#define INCLUDED_GR_BUFFER_PYTHON_HPP

#include <gnuradio/buffer.h>

void bind_buffer(py::module& m)
{
    using buffer    = gr::buffer;

    py::class_<buffer, std::shared_ptr<buffer>>(m, "buffer")
        .def("space_available",&buffer::space_available)
        .def("bufsize",&buffer::bufsize)
        .def("base",&buffer::base)
        .def("write_pointer",&buffer::write_pointer)
        .def("update_write_pointer",&buffer::update_write_pointer,
            py::arg("nitems") 
        )
        .def("set_done",&buffer::set_done,
            py::arg("done") 
        )
        .def("done",&buffer::done)
        .def("link",&buffer::link)
        .def("nreaders",&buffer::nreaders)
        .def("reader",&buffer::reader,
            py::arg("index") 
        )
        .def("mutex",&buffer::mutex)
        .def("nitems_written",&buffer::nitems_written)
        .def("reset_nitem_counter",&buffer::reset_nitem_counter)
        .def("get_sizeof_item",&buffer::get_sizeof_item)
        .def("add_item_tag",&buffer::add_item_tag,
            py::arg("tag") 
        )
        .def("remove_item_tag",&buffer::remove_item_tag,
            py::arg("tag"), 
            py::arg("id") 
        )
        .def("prune_tags",&buffer::prune_tags,
            py::arg("max_time") 
        )
        .def("get_tags_begin",&buffer::get_tags_begin)
        .def("get_tags_end",&buffer::get_tags_end)
        .def("get_tags_lower_bound",&buffer::get_tags_lower_bound,
            py::arg("x") 
        )
        .def("get_tags_upper_bound",&buffer::get_tags_upper_bound,
            py::arg("x") 
        )
        ;

    py::class_<buffer_reader, std::shared_ptr<buffer_reader>>(m, "buffer_reader")
        .def(py::init<gr::buffer_reader const &>(),
           py::arg("arg0") 
        )
        .def("declare_sample_delay",&buffer::declare_sample_delay,
            py::arg("delay") 
        )
        .def("sample_delay",&buffer::sample_delay)
        .def("items_available",&buffer::items_available)
        .def("buffer",&buffer::buffer)
        .def("max_possible_items_available",&buffer::max_possible_items_available)
        .def("read_pointer",&buffer::read_pointer)
        .def("update_read_pointer",&buffer::update_read_pointer,
            py::arg("nitems") 
        )
        .def("set_done",&buffer::set_done,
            py::arg("done") 
        )
        .def("done",&buffer::done)
        .def("mutex",&buffer::mutex)
        .def("nitems_read",&buffer::nitems_read)
        .def("reset_nitem_counter",&buffer::reset_nitem_counter)
        .def("get_sizeof_item",&buffer::get_sizeof_item)
        .def("link",&buffer::link)
        .def("get_tags_in_range",&buffer::get_tags_in_range,
            py::arg("v"), 
            py::arg("abs_start"), 
            py::arg("abs_end"), 
            py::arg("id") 
        )
        ;

    m.def("make_buffer",&gr::make_buffer,
        py::arg("nitems"), 
        py::arg("sizeof_item"), 
        py::arg("link") = gr::block_sptr() 
    );
    m.def("buffer_add_reader",&gr::buffer_add_reader,
        py::arg("buf"), 
        py::arg("nzero_preload"), 
        py::arg("link") = gr::block_sptr(), 
        py::arg("delay") = 0 
    );
    m.def("buffer_ncurrently_allocated",&gr::buffer_ncurrently_allocated);
    m.def("buffer_reader_ncurrently_allocated",&gr::buffer_reader_ncurrently_allocated);
} 

#endif /* INCLUDED_GR_BUFFER_PYTHON_HPP */
