

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_FEVAL_PYTHON_HPP
#define INCLUDED_GR_FEVAL_PYTHON_HPP

#include <gnuradio/feval.h>

void bind_feval(py::module& m)
{
    using feval_dd    = gr::feval_dd;
    using feval_cc    = gr::feval_cc;
    using feval_ll    = gr::feval_ll;
    using feval    = gr::feval;
    using feval_p    = gr::feval_p;


    py::class_<feval_dd, std::shared_ptr<feval_dd>>(m, "feval_dd")
        .def(py::init<>())
        .def(py::init<gr::feval_dd const &>(),
           py::arg("arg0") 
        )
        .def("calleval",&feval_dd::calleval,
            py::arg("x") 
        )
        ;


    py::class_<feval_cc, std::shared_ptr<feval_cc>>(m, "feval_cc")
        .def(py::init<>())
        .def(py::init<gr::feval_cc const &>(),
           py::arg("arg0") 
        )
        .def("calleval",&feval_cc::calleval,
            py::arg("x") 
        )
        ;


    py::class_<feval_ll, std::shared_ptr<feval_ll>>(m, "feval_ll")
        .def(py::init<>())
        .def(py::init<gr::feval_ll const &>(),
           py::arg("arg0") 
        )
        .def("calleval",&feval_ll::calleval,
            py::arg("x") 
        )
        ;


    py::class_<feval, std::shared_ptr<feval>>(m, "feval")
        .def(py::init<>())
        .def(py::init<gr::feval const &>(),
           py::arg("arg0") 
        )
        .def("calleval",&feval::calleval)
        ;


    py::class_<feval_p, std::shared_ptr<feval_p>>(m, "feval_p")
        .def(py::init<>())
        .def(py::init<gr::feval_p const &>(),
           py::arg("arg0") 
        )
        .def("calleval",&feval_p::calleval,
            py::arg("x") 
        )
        ;

    m.def("feval_dd_example",&gr::feval_dd_example,
        py::arg("f"), 
        py::arg("x") 
    );
    m.def("feval_cc_example",&gr::feval_cc_example,
        py::arg("f"), 
        py::arg("x") 
    );
    m.def("feval_ll_example",&gr::feval_ll_example,
        py::arg("f"), 
        py::arg("x") 
    );
    m.def("feval_example",&gr::feval_example,
        py::arg("f") 
    );
} 

#endif /* INCLUDED_GR_FEVAL_PYTHON_HPP */
