/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fxpt_vco.h>

void bind_fxpt_vco(py::module& m)
{
    using fxpt_vco    = gr::fxpt_vco;


    py::class_<fxpt_vco,
        std::shared_ptr<fxpt_vco>>(m, "fxpt_vco")

        .def(py::init<>())
        .def(py::init<gr::fxpt_vco const &>(),           py::arg("arg0") 
        )

        .def("set_phase",&fxpt_vco::set_phase,
            py::arg("angle") 
        )
        .def("adjust_phase",&fxpt_vco::adjust_phase,
            py::arg("delta_phase") 
        )
        .def("get_phase",&fxpt_vco::get_phase)
        .def("sincos",(void (fxpt_vco::*)(float *, float *) const)&fxpt_vco::sincos,
            py::arg("sinx"), 
            py::arg("cosx") 
        )
        .def("sincos",(void (fxpt_vco::*)(gr_complex *, float const *, int, float, float))&fxpt_vco::sincos,
            py::arg("output"), 
            py::arg("input"), 
            py::arg("noutput_items"), 
            py::arg("k"), 
            py::arg("ampl") = 1. 
        )
        .def("cos",(void (fxpt_vco::*)(float *, float const *, int, float, float))&fxpt_vco::cos,
            py::arg("output"), 
            py::arg("input"), 
            py::arg("noutput_items"), 
            py::arg("k"), 
            py::arg("ampl") = 1. 
        )
        .def("cos",(float (fxpt_vco::*)() const)&fxpt_vco::cos)
        .def("sin",&fxpt_vco::sin)
        ;


} 
