

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_IO_SIGNATURE_PYTHON_HPP
#define INCLUDED_GR_IO_SIGNATURE_PYTHON_HPP

#include <gnuradio/io_signature.h>

void bind_io_signature(py::module& m)
{
    using io_signature    = gr::io_signature;

    // py::class_<io_signature, std::shared_ptr<io_signature>>(m, "io_signaturev")
    //     .def(py::init(&io_signature::makev),
    //        py::arg("min_streams"),
    //        py::arg("max_streams"),
    //        py::arg("sizeof_stream_items")
    //     )
    //     ;

    py::class_<io_signature, std::shared_ptr<io_signature>>(m, "io_signature")
        .def(py::init(&io_signature::make),
           py::arg("min_streams"),
           py::arg("max_streams"),
           py::arg("sizeof_stream_item")
        )
        .def("make",&io_signature::make)  // todo - make static and put back args
        .def("make2",&io_signature::make2)
        .def("make3",&io_signature::make3)
        .def("makev",&io_signature::makev)
        .def("min_streams",&io_signature::min_streams)
        .def("max_streams",&io_signature::max_streams)
        .def("sizeof_stream_item",&io_signature::sizeof_stream_item,
            py::arg("index") 
        )
        .def("sizeof_stream_items",&io_signature::sizeof_stream_items)
        ;

} 

#endif /* INCLUDED_GR_IO_SIGNATURE_PYTHON_HPP */
