/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/io_signature.h>

void bind_io_signature(py::module& m)
{
    using io_signature    = gr::io_signature;


    py::class_<io_signature,
        std::shared_ptr<io_signature>>(m, "io_signature")

        .def(py::init(&io_signature::make),
           py::arg("min_streams"), 
           py::arg("max_streams"), 
           py::arg("sizeof_stream_item") 
        )
        

        .def_static("make2",&io_signature::make2,
            py::arg("min_streams"), 
            py::arg("max_streams"), 
            py::arg("sizeof_stream_item1"), 
            py::arg("sizeof_stream_item2") 
        )
        .def_static("make3",&io_signature::make3,
            py::arg("min_streams"), 
            py::arg("max_streams"), 
            py::arg("sizeof_stream_item1"), 
            py::arg("sizeof_stream_item2"), 
            py::arg("sizeof_stream_item3") 
        )
        .def_static("makev",&io_signature::makev,
            py::arg("min_streams"), 
            py::arg("max_streams"), 
            py::arg("sizeof_stream_items") 
        )
        .def("min_streams",&io_signature::min_streams)
        .def("max_streams",&io_signature::max_streams)
        .def("sizeof_stream_item",&io_signature::sizeof_stream_item,
            py::arg("index") 
        )
        .def("sizeof_stream_items",&io_signature::sizeof_stream_items)
        ;


} 
