

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_MSG_QUEUE_PYTHON_HPP
#define INCLUDED_GR_MSG_QUEUE_PYTHON_HPP

#include <gnuradio/msg_queue.h>

void bind_msg_queue(py::module& m)
{
    using msg_queue    = gr::msg_queue;


    py::class_<msg_queue, std::shared_ptr<msg_queue>>(m, "msg_queue")
        .def(py::init(&gr::msg_queue::make),
           py::arg("limit") = 0
        )
        .def("handle",&msg_queue::handle,
            py::arg("msg") 
        )
        .def("insert_tail",&msg_queue::insert_tail,
            py::arg("msg") 
        )
        .def("delete_head",&msg_queue::delete_head)
        .def("delete_head_nowait",&msg_queue::delete_head_nowait)
        .def("flush",&msg_queue::flush)
        .def("empty_p",&msg_queue::empty_p)
        .def("full_p",&msg_queue::full_p)
        .def("count",&msg_queue::count)
        .def("limit",&msg_queue::limit)
        ;

} 

#endif /* INCLUDED_GR_MSG_QUEUE_PYTHON_HPP */
