/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/msg_handler.h>

void bind_msg_handler(py::module& m)
{
    using msg_handler    = gr::msg_handler;


    py::class_<msg_handler,
        std::shared_ptr<msg_handler>>(m, "msg_handler")
        
        .def("handle",&msg_handler::handle,
            py::arg("msg") 
        )
        ;


} 
