/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/prefs.h>

void bind_prefs(py::module& m)
{
    using prefs    = gr::prefs;


    py::class_<prefs,
        std::shared_ptr<prefs>>(m, "prefs")

        .def(py::init<>())

        .def("singleton",&prefs::singleton)
        .def("add_config_file",&prefs::add_config_file,
            py::arg("configfile") 
        )
        .def("to_string",&prefs::to_string)
        .def("save",&prefs::save)
        .def("has_section",&prefs::has_section,
            py::arg("section") 
        )
        .def("has_option",&prefs::has_option,
            py::arg("section"), 
            py::arg("option") 
        )
        .def("get_string",&prefs::get_string,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("default_val") 
        )
        .def("set_string",&prefs::set_string,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("val") 
        )
        .def("get_bool",&prefs::get_bool,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("default_val") 
        )
        .def("set_bool",&prefs::set_bool,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("val") 
        )
        .def("get_long",&prefs::get_long,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("default_val") 
        )
        .def("set_long",&prefs::set_long,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("val") 
        )
        .def("get_double",&prefs::get_double,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("default_val") 
        )
        .def("set_double",&prefs::set_double,
            py::arg("section"), 
            py::arg("option"), 
            py::arg("val") 
        )
        ;


} 
