/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/random.h>

void bind_random(py::module& m)
{
    using random    = gr::random;


    py::class_<random,
        std::shared_ptr<random>>(m, "random")

        .def(py::init<unsigned int,int,int>(),           py::arg("seed") = 0, 
           py::arg("min_integer") = 0, 
           py::arg("max_integer") = 2 
        )
        .def(py::init<gr::random const &>(),           py::arg("arg0") 
        )

        .def("reseed",&random::reseed,
            py::arg("seed") 
        )
        .def("set_integer_limits",&random::set_integer_limits,
            py::arg("minimum"), 
            py::arg("maximum") 
        )
        .def("ran_int",&random::ran_int)
        .def("ran1",&random::ran1)
        .def("gasdev",&random::gasdev)
        .def("laplacian",&random::laplacian)
        .def("rayleigh",&random::rayleigh)
        .def("impulse",&random::impulse,
            py::arg("factor") 
        )
        .def("rayleigh_complex",&random::rayleigh_complex)
        ;


} 
