/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/realtime_impl.h>

void bind_realtime_impl(py::module& m)
{
    using rt_sched_param    = gr::rt_sched_param;


    py::class_<rt_sched_param,
        std::shared_ptr<rt_sched_param>>(m, "rt_sched_param")

        .def(py::init<>())
        .def(py::init<int,gr::rt_sched_policy>(),           py::arg("priority_"), 
           py::arg("policy_") = ::gr::rt_sched_policy::RT_SCHED_RR 
        )
        .def(py::init<gr::impl::rt_sched_param const &>(),           py::arg("arg0") 
        )

        ;

    py::enum_<gr::rt_status_t>(m,"rt_status_t")
        .value("RT_OK", gr::RT_OK) // 0
        .value("RT_NOT_IMPLEMENTED", gr::RT_NOT_IMPLEMENTED) // 1
        .value("RT_NO_PRIVS", gr::RT_NO_PRIVS) // 2
        .value("RT_OTHER_ERROR", gr::RT_OTHER_ERROR) // 3
        .export_values()
    ;
    py::enum_<gr::rt_sched_policy>(m,"rt_sched_policy")
        .value("RT_SCHED_RR", gr::RT_SCHED_RR) // 0
        .value("RT_SCHED_FIFO", gr::RT_SCHED_FIFO) // 1
        .export_values()
    ;

    m.def("rt_priority_min",&gr::rt_priority_min);
    m.def("rt_priority_max",&gr::rt_priority_max);
    m.def("rt_priority_default",&gr::rt_priority_default);
    m.def("enable_realtime_scheduling",&gr::enable_realtime_scheduling,
        py::arg("arg0") = gr::impl::rt_sched_param() 
    );
} 
