/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sincos.h>

void bind_sincos(py::module& m)
{


    m.def("sincos",&gr::sincos,
        py::arg("x"), 
        py::arg("sin"), 
        py::arg("cos") 
    );
    m.def("sincosf",&gr::sincosf,
        py::arg("x"), 
        py::arg("sin"), 
        py::arg("cos") 
    );
} 
