/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sync_decimator.h>

void bind_sync_decimator(py::module& m)
{
    using sync_decimator    = gr::sync_decimator;


    py::class_<sync_decimator,gr::sync_block,
        std::shared_ptr<sync_decimator>>(m, "sync_decimator")


        .def("decimation",&sync_decimator::decimation)
        .def("set_decimation",&sync_decimator::set_decimation,
            py::arg("decimation") 
        )
        .def("forecast",&sync_decimator::forecast,
            py::arg("noutput_items"), 
            py::arg("ninput_items_required") 
        )
        .def("general_work",&sync_decimator::general_work,
            py::arg("noutput_items"), 
            py::arg("ninput_items"), 
            py::arg("input_items"), 
            py::arg("output_items") 
        )
        .def("fixed_rate_ninput_to_noutput",&sync_decimator::fixed_rate_ninput_to_noutput,
            py::arg("ninput") 
        )
        .def("fixed_rate_noutput_to_ninput",&sync_decimator::fixed_rate_noutput_to_ninput,
            py::arg("noutput") 
        )
        .def("to_basic_block",[](std::shared_ptr<sync_decimator> p){
            return p->to_basic_block();
        })
        ;


} 
