/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sync_block.h>

void bind_sync_block(py::module& m)
{
    using sync_block    = gr::sync_block;


    py::class_<sync_block,gr::block,
        std::shared_ptr<sync_block>>(m, "sync_block")


        .def("work",&sync_block::work,
            py::arg("noutput_items"), 
            py::arg("input_items"), 
            py::arg("output_items") 
        )
        .def("forecast",&sync_block::forecast,
            py::arg("noutput_items"), 
            py::arg("ninput_items_required") 
        )
        .def("general_work",&sync_block::general_work,
            py::arg("noutput_items"), 
            py::arg("ninput_items"), 
            py::arg("input_items"), 
            py::arg("output_items") 
        )
        .def("fixed_rate_ninput_to_noutput",&sync_block::fixed_rate_ninput_to_noutput,
            py::arg("ninput") 
        )
        .def("fixed_rate_noutput_to_ninput",&sync_block::fixed_rate_noutput_to_ninput,
            py::arg("noutput") 
        )
        .def("to_basic_block",[](std::shared_ptr<sync_block> p){
            return p->to_basic_block();
        })
        ;


} 
