

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_TAGGED_STREAM_BLOCK_PYTHON_HPP
#define INCLUDED_GR_TAGGED_STREAM_BLOCK_PYTHON_HPP

#include <gnuradio/tagged_stream_block.h>

void bind_tagged_stream_block(py::module& m)
{
    using tagged_stream_block    = gr::tagged_stream_block;


    py::class_<tagged_stream_block, std::shared_ptr<tagged_stream_block>>(m, "tagged_stream_block")
        .def("forecast",&tagged_stream_block::forecast,
            py::arg("noutput_items"), 
            py::arg("ninput_items_required") 
        )
        .def("check_topology",&tagged_stream_block::check_topology,
            py::arg("ninputs"), 
            py::arg("arg1") 
        )
        .def("general_work",&tagged_stream_block::general_work,
            py::arg("noutput_items"), 
            py::arg("ninput_items"), 
            py::arg("input_items"), 
            py::arg("output_items") 
        )
        .def("work",&tagged_stream_block::work,
            py::arg("noutput_items"), 
            py::arg("ninput_items"), 
            py::arg("input_items"), 
            py::arg("output_items") 
        )
        ;

} 

#endif /* INCLUDED_GR_TAGGED_STREAM_BLOCK_PYTHON_HPP */
