

/* Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */


/* This file is automatically generated using the gen_nonblock_bindings.py tool */

#ifndef INCLUDED_GR_TAGS_PYTHON_HPP
#define INCLUDED_GR_TAGS_PYTHON_HPP

#include <gnuradio/tags.h>

void bind_tags(py::module& m)
{
    using tag_t    = gr::tag_t;


    py::class_<tag_t, std::shared_ptr<tag_t>>(m, "tag_t")
        .def(py::init<>())
        .def(py::init<gr::tag_t const &>(),
           py::arg("rhs") 
        )
        // .def("offset_compare",&tag_t::offset_compare,
        //     py::arg("x"), 
        //     py::arg("y") 
        // )
        .def("offset_compare",&tag_t::offset_compare)
        .def_readwrite("offset", &tag_t::offset)
        .def_readwrite("key", &tag_t::key)
        .def_readwrite("value", &tag_t::value)
        .def_readwrite("srcid", &tag_t::srcid)
        .def_readwrite("marked_deleted", &tag_t::marked_deleted)
        ;

} 

#endif /* INCLUDED_GR_TAGS_PYTHON_HPP */
