/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fft/ctrlport_probe_psd.h>

void bind_ctrlport_probe_psd(py::module& m)
{
    using ctrlport_probe_psd    = gr::fft::ctrlport_probe_psd;


    py::class_<ctrlport_probe_psd,gr::sync_block,
        std::shared_ptr<ctrlport_probe_psd>>(m, "ctrlport_probe_psd")

        .def(py::init(&ctrlport_probe_psd::make),
           py::arg("id"), 
           py::arg("desc"), 
           py::arg("len") 
        )
        

        .def("get",&ctrlport_probe_psd::get)
        .def("set_length",&ctrlport_probe_psd::set_length,
            py::arg("len") 
        )
        .def("to_basic_block",[](std::shared_ptr<ctrlport_probe_psd> p){
            return p->to_basic_block();
        })
        ;


} 
