/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/pybind11.h>
#include <pybind11/complex.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fft/goertzel.h>

void bind_goertzel(py::module& m)
{
    using goertzel    = gr::fft::goertzel;


    py::class_<goertzel,
        std::shared_ptr<goertzel>>(m, "goertzel")

        .def(py::init<int,int,float>(),           py::arg("rate"), 
           py::arg("len"), 
           py::arg("freq") 
        )
        .def(py::init<gr::fft::goertzel const &>(),           py::arg("arg0") 
        )

        .def("set_params",&goertzel::set_params,
            py::arg("rate"), 
            py::arg("len"), 
            py::arg("freq") 
        )
        .def("batch",&goertzel::batch,
            py::arg("in") 
        )
        .def("input",&goertzel::input,
            py::arg("in") 
        )
        .def("output",&goertzel::output)
        .def("ready",&goertzel::ready)
        ;


} 
